using System;

namespace StatisticMod
{
    internal static partial class ModLocalization
    {
        // Tłumaczenia interfejsu PODSUMOWANIE i wykresów SKLEP.
        // Polski i angielski są przekazywane bezpośrednio przez Plugin.T.
        private static void AddDailySummaryTerms()
        {
            AddDailySummaryTermsGroup1();
            AddDailySummaryTermsGroup2();
            AddDailySummaryTermsGroup3();
            AddDailySummaryTermsGroup4();
            AddDailySummaryTermsGroup5();
            AddDailySummaryTermsGroup6();
        }

        private static void AddDailySummaryTermsGroup1()
        {
            SetDailySummaryTerms("fr",
                "NO SUMMARY", "Aucun résumé",
                "The summary will appear after the day is finished.", "Le résumé apparaîtra après la fin de la journée.",
                "CUSTOMERS", "Clients",
                "Satisfied", "Satisfaits",
                "SATISFACTION", "Satisfaction",
                "PRODUCT ISSUES", "Problèmes de produits",
                "Not found", "Introuvables",
                "Too expensive", "Trop chers",
                "SERVICE ISSUES", "Problèmes de service",
                "Short change", "Monnaie incorrecte",
                "Harmed", "Lésés",
                "STORE POINTS", "Points du magasin",
                "Points earned that day", "Points gagnés ce jour-là",
                "CHECKOUT INCOME", "Revenus des caisses",
                "Checkout sales", "Ventes aux caisses",
                "OTHER INCOME", "Autres revenus",
                "Vending", "Distributeurs",
                "Loans", "Prêts",
                "TOTAL INCOME", "Revenus totaux",
                "Checkout + vending + loans", "Caisses + distributeurs + prêts",
                "SUPPLIES", "Approvisionnement",
                "Cost of ordered stock", "Coût du stock commandé",
                "STAFF", "Personnel",
                "Employee wages", "Salaires des employés",
                "RENT AND BILLS", "Loyer et factures",
                "Rent", "Loyer",
                "Bills", "Factures",
                "INVESTMENTS", "Investissements",
                "Upgrades", "Améliorations",
                "Customization", "Personnalisation",
                "LOAN PAYMENT", "Remboursement du prêt",
                "Payment made that day", "Paiement effectué ce jour-là",
                "TOTAL EXPENSES", "Dépenses totales",
                "Sum of all recorded costs", "Somme de tous les coûts enregistrés",
                "DAILY PROFIT", "Bénéfice du jour",
                "Mod calculation", "Calcul du mod",
                "BALANCE", "Solde",
                "Account balance after the day", "Solde du compte après la journée",
                "STORE", "Magasin",
                "View", "Vue",
                "Store results over time", "Résultats du magasin dans le temps",
                "Product results over time", "Résultats du produit dans le temps",
                "Total customers", "Total des clients",
                "Satisfied customers", "Clients satisfaits",
                "Satisfaction rate", "Taux de satisfaction",
                "Products not found", "Produits introuvables",
                "Products too expensive", "Produits trop chers",
                "Incorrect change", "Monnaie incorrecte",
                "Harmed customers", "Clients lésés",
                "Vending income", "Revenus des distributeurs",
                "Loan income", "Revenu du prêt",
                "Supply costs", "Coûts d’approvisionnement",
                "Staff payment", "Coûts du personnel",
                "Paint costs", "Coûts de peinture",
                "Floor costs", "Coûts des sols",
                "pts", "pts",
                "Latest value", "Dernière valeur",
                "Weighted average", "Moyenne pondérée",
                "Total", "Total",
                "No saved daily summaries.", "Aucun résumé journalier enregistré.",
                "SUMMARY", "Résumé");

            SetDailySummaryTerms("it",
                "NO SUMMARY", "Nessun riepilogo",
                "The summary will appear after the day is finished.", "Il riepilogo apparirà al termine della giornata.",
                "CUSTOMERS", "Clienti",
                "Satisfied", "Soddisfatti",
                "SATISFACTION", "Soddisfazione",
                "PRODUCT ISSUES", "Problemi prodotti",
                "Not found", "Non trovati",
                "Too expensive", "Troppo costosi",
                "SERVICE ISSUES", "Problemi di servizio",
                "Short change", "Resto errato",
                "Harmed", "Danneggiati",
                "STORE POINTS", "Punti negozio",
                "Points earned that day", "Punti ottenuti quel giorno",
                "CHECKOUT INCOME", "Incasso casse",
                "Checkout sales", "Vendite alle casse",
                "OTHER INCOME", "Altri ricavi",
                "Vending", "Distributori",
                "Loans", "Prestiti",
                "TOTAL INCOME", "Ricavi totali",
                "Checkout + vending + loans", "Casse + distributori + prestiti",
                "SUPPLIES", "Forniture",
                "Cost of ordered stock", "Costo della merce ordinata",
                "STAFF", "Personale",
                "Employee wages", "Stipendi dei dipendenti",
                "RENT AND BILLS", "Affitto e bollette",
                "Rent", "Affitto",
                "Bills", "Bollette",
                "INVESTMENTS", "Investimenti",
                "Upgrades", "Migliorie",
                "Customization", "Personalizzazione",
                "LOAN PAYMENT", "Rimborso prestito",
                "Payment made that day", "Pagamento effettuato quel giorno",
                "TOTAL EXPENSES", "Spese totali",
                "Sum of all recorded costs", "Somma di tutti i costi registrati",
                "DAILY PROFIT", "Profitto giornaliero",
                "Mod calculation", "Calcolo del mod",
                "BALANCE", "Saldo",
                "Account balance after the day", "Saldo del conto a fine giornata",
                "STORE", "Negozio",
                "View", "Vista",
                "Store results over time", "Andamento dei risultati del negozio",
                "Product results over time", "Andamento dei risultati del prodotto",
                "Total customers", "Clienti totali",
                "Satisfied customers", "Clienti soddisfatti",
                "Satisfaction rate", "Tasso di soddisfazione",
                "Products not found", "Prodotti non trovati",
                "Products too expensive", "Prodotti troppo costosi",
                "Incorrect change", "Resto errato",
                "Harmed customers", "Clienti danneggiati",
                "Vending income", "Ricavi dei distributori",
                "Loan income", "Entrate da prestito",
                "Supply costs", "Costi delle forniture",
                "Staff payment", "Costi del personale",
                "Paint costs", "Costi di verniciatura",
                "Floor costs", "Costi dei pavimenti",
                "pts", "pt",
                "Latest value", "Ultimo valore",
                "Weighted average", "Media ponderata",
                "Total", "Totale",
                "No saved daily summaries.", "Nessun riepilogo giornaliero salvato.",
                "SUMMARY", "Riepilogo");

            SetDailySummaryTerms("de",
                "NO SUMMARY", "Keine Zusammenfassung",
                "The summary will appear after the day is finished.", "Die Zusammenfassung erscheint nach Tagesende.",
                "CUSTOMERS", "Kunden",
                "Satisfied", "Zufrieden",
                "SATISFACTION", "Zufriedenheit",
                "PRODUCT ISSUES", "Produktprobleme",
                "Not found", "Nicht gefunden",
                "Too expensive", "Zu teuer",
                "SERVICE ISSUES", "Serviceprobleme",
                "Short change", "Falsches Wechselgeld",
                "Harmed", "Geschädigt",
                "STORE POINTS", "Ladenpunkte",
                "Points earned that day", "An diesem Tag verdiente Punkte",
                "CHECKOUT INCOME", "Kasseneinnahmen",
                "Checkout sales", "Verkäufe an Kassen",
                "OTHER INCOME", "Sonstige Einnahmen",
                "Vending", "Automaten",
                "Loans", "Kredite",
                "TOTAL INCOME", "Gesamteinnahmen",
                "Checkout + vending + loans", "Kassen + Automaten + Kredite",
                "SUPPLIES", "Warenbeschaffung",
                "Cost of ordered stock", "Kosten der bestellten Ware",
                "STAFF", "Personal",
                "Employee wages", "Mitarbeiterlöhne",
                "RENT AND BILLS", "Miete und Rechnungen",
                "Rent", "Miete",
                "Bills", "Rechnungen",
                "INVESTMENTS", "Investitionen",
                "Upgrades", "Upgrades",
                "Customization", "Anpassungen",
                "LOAN PAYMENT", "Kredittilgung",
                "Payment made that day", "An diesem Tag geleistete Zahlung",
                "TOTAL EXPENSES", "Gesamtausgaben",
                "Sum of all recorded costs", "Summe aller erfassten Kosten",
                "DAILY PROFIT", "Tagesgewinn",
                "Mod calculation", "Mod-Berechnung",
                "BALANCE", "Kontostand",
                "Account balance after the day", "Kontostand nach Tagesende",
                "STORE", "Laden",
                "View", "Ansicht",
                "Store results over time", "Ladenentwicklung im Zeitverlauf",
                "Product results over time", "Produktentwicklung im Zeitverlauf",
                "Total customers", "Kunden insgesamt",
                "Satisfied customers", "Zufriedene Kunden",
                "Satisfaction rate", "Zufriedenheitsrate",
                "Products not found", "Nicht gefundene Produkte",
                "Products too expensive", "Zu teure Produkte",
                "Incorrect change", "Falsches Wechselgeld",
                "Harmed customers", "Geschädigte Kunden",
                "Vending income", "Automateneinnahmen",
                "Loan income", "Krediteinnahmen",
                "Supply costs", "Beschaffungskosten",
                "Staff payment", "Personalkosten",
                "Paint costs", "Anstrichkosten",
                "Floor costs", "Bodenkosten",
                "pts", "Pkt.",
                "Latest value", "Letzter Wert",
                "Weighted average", "Gewichteter Durchschnitt",
                "Total", "Gesamt",
                "No saved daily summaries.", "Keine gespeicherten Tageszusammenfassungen.",
                "SUMMARY", "Zusammenfassung");

        }

        private static void AddDailySummaryTermsGroup2()
        {
            SetDailySummaryTerms("es",
                "NO SUMMARY", "Sin resumen",
                "The summary will appear after the day is finished.", "El resumen aparecerá al finalizar el día.",
                "CUSTOMERS", "Clientes",
                "Satisfied", "Satisfechos",
                "SATISFACTION", "Satisfacción",
                "PRODUCT ISSUES", "Problemas de productos",
                "Not found", "No encontrados",
                "Too expensive", "Demasiado caros",
                "SERVICE ISSUES", "Problemas de atención",
                "Short change", "Cambio incorrecto",
                "Harmed", "Perjudicados",
                "STORE POINTS", "Puntos de tienda",
                "Points earned that day", "Puntos obtenidos ese día",
                "CHECKOUT INCOME", "Ingresos de cajas",
                "Checkout sales", "Ventas en cajas",
                "OTHER INCOME", "Otros ingresos",
                "Vending", "Máquinas expendedoras",
                "Loans", "Préstamos",
                "TOTAL INCOME", "Ingresos totales",
                "Checkout + vending + loans", "Cajas + máquinas + préstamos",
                "SUPPLIES", "Suministros",
                "Cost of ordered stock", "Coste del stock pedido",
                "STAFF", "Personal",
                "Employee wages", "Salarios de empleados",
                "RENT AND BILLS", "Alquiler y facturas",
                "Rent", "Alquiler",
                "Bills", "Facturas",
                "INVESTMENTS", "Inversiones",
                "Upgrades", "Mejoras",
                "Customization", "Personalización",
                "LOAN PAYMENT", "Pago del préstamo",
                "Payment made that day", "Pago realizado ese día",
                "TOTAL EXPENSES", "Gastos totales",
                "Sum of all recorded costs", "Suma de todos los costes registrados",
                "DAILY PROFIT", "Beneficio diario",
                "Mod calculation", "Cálculo del mod",
                "BALANCE", "Saldo",
                "Account balance after the day", "Saldo de la cuenta al finalizar el día",
                "STORE", "Tienda",
                "View", "Vista",
                "Store results over time", "Resultados de la tienda a lo largo del tiempo",
                "Product results over time", "Resultados del producto a lo largo del tiempo",
                "Total customers", "Clientes totales",
                "Satisfied customers", "Clientes satisfechos",
                "Satisfaction rate", "Tasa de satisfacción",
                "Products not found", "Productos no encontrados",
                "Products too expensive", "Productos demasiado caros",
                "Incorrect change", "Cambio incorrecto",
                "Harmed customers", "Clientes perjudicados",
                "Vending income", "Ingresos de máquinas",
                "Loan income", "Ingresos por préstamo",
                "Supply costs", "Costes de suministros",
                "Staff payment", "Costes de personal",
                "Paint costs", "Costes de pintura",
                "Floor costs", "Costes de suelo",
                "pts", "pts",
                "Latest value", "Último valor",
                "Weighted average", "Media ponderada",
                "Total", "Total",
                "No saved daily summaries.", "No hay resúmenes diarios guardados.",
                "SUMMARY", "Resumen");

            SetDailySummaryTerms("zh",
                "NO SUMMARY", "无汇总",
                "The summary will appear after the day is finished.", "日结后将显示汇总。",
                "CUSTOMERS", "顾客",
                "Satisfied", "满意",
                "SATISFACTION", "满意度",
                "PRODUCT ISSUES", "商品问题",
                "Not found", "未找到",
                "Too expensive", "价格过高",
                "SERVICE ISSUES", "服务问题",
                "Short change", "找零错误",
                "Harmed", "受损",
                "STORE POINTS", "商店点数",
                "Points earned that day", "当日获得的点数",
                "CHECKOUT INCOME", "收银收入",
                "Checkout sales", "收银台销售额",
                "OTHER INCOME", "其他收入",
                "Vending", "自动售货机",
                "Loans", "贷款",
                "TOTAL INCOME", "总收入",
                "Checkout + vending + loans", "收银 + 售货机 + 贷款",
                "SUPPLIES", "进货",
                "Cost of ordered stock", "订购库存成本",
                "STAFF", "员工",
                "Employee wages", "员工工资",
                "RENT AND BILLS", "租金和账单",
                "Rent", "租金",
                "Bills", "账单",
                "INVESTMENTS", "投资",
                "Upgrades", "升级",
                "Customization", "自定义",
                "LOAN PAYMENT", "贷款还款",
                "Payment made that day", "当日支付金额",
                "TOTAL EXPENSES", "总支出",
                "Sum of all recorded costs", "所有已记录成本之和",
                "DAILY PROFIT", "当日利润",
                "Mod calculation", "模组计算值",
                "BALANCE", "余额",
                "Account balance after the day", "日结后的账户余额",
                "STORE", "商店",
                "View", "视图",
                "Store results over time", "商店业绩趋势",
                "Product results over time", "商品业绩趋势",
                "Total customers", "顾客总数",
                "Satisfied customers", "满意顾客",
                "Satisfaction rate", "满意率",
                "Products not found", "未找到商品",
                "Products too expensive", "商品价格过高",
                "Incorrect change", "找零错误",
                "Harmed customers", "受损顾客",
                "Vending income", "售货机收入",
                "Loan income", "贷款收入",
                "Supply costs", "进货成本",
                "Staff payment", "员工支出",
                "Paint costs", "油漆成本",
                "Floor costs", "地板成本",
                "pts", "点",
                "Latest value", "最新值",
                "Weighted average", "加权平均",
                "Total", "总计",
                "No saved daily summaries.", "没有已保存的每日汇总。",
                "SUMMARY", "汇总");

            SetDailySummaryTerms("pt-BR",
                "NO SUMMARY", "Sem resumo",
                "The summary will appear after the day is finished.", "O resumo aparecerá após o fim do dia.",
                "CUSTOMERS", "Clientes",
                "Satisfied", "Satisfeitos",
                "SATISFACTION", "Satisfação",
                "PRODUCT ISSUES", "Problemas com produtos",
                "Not found", "Não encontrados",
                "Too expensive", "Caros demais",
                "SERVICE ISSUES", "Problemas de atendimento",
                "Short change", "Troco incorreto",
                "Harmed", "Prejudicados",
                "STORE POINTS", "Pontos da loja",
                "Points earned that day", "Pontos ganhos naquele dia",
                "CHECKOUT INCOME", "Receita dos caixas",
                "Checkout sales", "Vendas nos caixas",
                "OTHER INCOME", "Outras receitas",
                "Vending", "Máquinas de venda",
                "Loans", "Empréstimos",
                "TOTAL INCOME", "Receita total",
                "Checkout + vending + loans", "Caixas + máquinas + empréstimos",
                "SUPPLIES", "Abastecimento",
                "Cost of ordered stock", "Custo do estoque pedido",
                "STAFF", "Funcionários",
                "Employee wages", "Salários dos funcionários",
                "RENT AND BILLS", "Aluguel e contas",
                "Rent", "Aluguel",
                "Bills", "Contas",
                "INVESTMENTS", "Investimentos",
                "Upgrades", "Melhorias",
                "Customization", "Personalização",
                "LOAN PAYMENT", "Pagamento do empréstimo",
                "Payment made that day", "Pagamento feito naquele dia",
                "TOTAL EXPENSES", "Despesas totais",
                "Sum of all recorded costs", "Soma de todos os custos registrados",
                "DAILY PROFIT", "Lucro diário",
                "Mod calculation", "Cálculo do mod",
                "BALANCE", "Saldo",
                "Account balance after the day", "Saldo da conta após o dia",
                "STORE", "Loja",
                "View", "Visualização",
                "Store results over time", "Resultados da loja ao longo do tempo",
                "Product results over time", "Resultados do produto ao longo do tempo",
                "Total customers", "Total de clientes",
                "Satisfied customers", "Clientes satisfeitos",
                "Satisfaction rate", "Taxa de satisfação",
                "Products not found", "Produtos não encontrados",
                "Products too expensive", "Produtos caros demais",
                "Incorrect change", "Troco incorreto",
                "Harmed customers", "Clientes prejudicados",
                "Vending income", "Receita das máquinas",
                "Loan income", "Receita de empréstimo",
                "Supply costs", "Custos de abastecimento",
                "Staff payment", "Pagamento de funcionários",
                "Paint costs", "Custos de pintura",
                "Floor costs", "Custos de piso",
                "pts", "pts",
                "Latest value", "Valor mais recente",
                "Weighted average", "Média ponderada",
                "Total", "Total",
                "No saved daily summaries.", "Nenhum resumo diário salvo.",
                "SUMMARY", "Resumo");

        }

        private static void AddDailySummaryTermsGroup3()
        {
            SetDailySummaryTerms("nl",
                "NO SUMMARY", "Geen samenvatting",
                "The summary will appear after the day is finished.", "De samenvatting verschijnt nadat de dag is afgelopen.",
                "CUSTOMERS", "Klanten",
                "Satisfied", "Tevreden",
                "SATISFACTION", "Tevredenheid",
                "PRODUCT ISSUES", "Productproblemen",
                "Not found", "Niet gevonden",
                "Too expensive", "Te duur",
                "SERVICE ISSUES", "Serviceproblemen",
                "Short change", "Onjuist wisselgeld",
                "Harmed", "Benadeeld",
                "STORE POINTS", "Winkelpunten",
                "Points earned that day", "Punten verdiend op die dag",
                "CHECKOUT INCOME", "Kassa-inkomsten",
                "Checkout sales", "Kassaverkoop",
                "OTHER INCOME", "Overige inkomsten",
                "Vending", "Automaten",
                "Loans", "Leningen",
                "TOTAL INCOME", "Totale inkomsten",
                "Checkout + vending + loans", "Kassa + automaten + leningen",
                "SUPPLIES", "Bevoorrading",
                "Cost of ordered stock", "Kosten van bestelde voorraad",
                "STAFF", "Personeel",
                "Employee wages", "Lonen van werknemers",
                "RENT AND BILLS", "Huur en rekeningen",
                "Rent", "Huur",
                "Bills", "Rekeningen",
                "INVESTMENTS", "Investeringen",
                "Upgrades", "Upgrades",
                "Customization", "Aanpassingen",
                "LOAN PAYMENT", "Aflossing lening",
                "Payment made that day", "Betaling op die dag",
                "TOTAL EXPENSES", "Totale uitgaven",
                "Sum of all recorded costs", "Som van alle geregistreerde kosten",
                "DAILY PROFIT", "Dagwinst",
                "Mod calculation", "Modberekening",
                "BALANCE", "Saldo",
                "Account balance after the day", "Rekeningsaldo na de dag",
                "STORE", "Winkel",
                "View", "Weergave",
                "Store results over time", "Winkelresultaten in de tijd",
                "Product results over time", "Productresultaten in de tijd",
                "Total customers", "Totaal klanten",
                "Satisfied customers", "Tevreden klanten",
                "Satisfaction rate", "Tevredenheidspercentage",
                "Products not found", "Producten niet gevonden",
                "Products too expensive", "Producten te duur",
                "Incorrect change", "Onjuist wisselgeld",
                "Harmed customers", "Benadeelde klanten",
                "Vending income", "Automateninkomsten",
                "Loan income", "Leninginkomsten",
                "Supply costs", "Bevoorradingskosten",
                "Staff payment", "Personeelskosten",
                "Paint costs", "Schilderkosten",
                "Floor costs", "Vloerkosten",
                "pts", "pnt",
                "Latest value", "Laatste waarde",
                "Weighted average", "Gewogen gemiddelde",
                "Total", "Totaal",
                "No saved daily summaries.", "Geen opgeslagen dagsamenvattingen.",
                "SUMMARY", "Samenvatting");

            SetDailySummaryTerms("ja",
                "NO SUMMARY", "集計なし",
                "The summary will appear after the day is finished.", "一日の終了後に集計が表示されます。",
                "CUSTOMERS", "顧客",
                "Satisfied", "満足",
                "SATISFACTION", "満足度",
                "PRODUCT ISSUES", "商品問題",
                "Not found", "見つからない",
                "Too expensive", "高すぎる",
                "SERVICE ISSUES", "接客問題",
                "Short change", "お釣りミス",
                "Harmed", "被害",
                "STORE POINTS", "店舗ポイント",
                "Points earned that day", "その日に獲得したポイント",
                "CHECKOUT INCOME", "レジ収入",
                "Checkout sales", "レジ売上",
                "OTHER INCOME", "その他の収入",
                "Vending", "自動販売機",
                "Loans", "ローン",
                "TOTAL INCOME", "総収入",
                "Checkout + vending + loans", "レジ + 自販機 + ローン",
                "SUPPLIES", "仕入れ",
                "Cost of ordered stock", "注文した在庫の費用",
                "STAFF", "スタッフ",
                "Employee wages", "従業員の賃金",
                "RENT AND BILLS", "家賃と請求書",
                "Rent", "家賃",
                "Bills", "請求書",
                "INVESTMENTS", "投資",
                "Upgrades", "アップグレード",
                "Customization", "カスタマイズ",
                "LOAN PAYMENT", "ローン返済",
                "Payment made that day", "その日に行った支払い",
                "TOTAL EXPENSES", "総支出",
                "Sum of all recorded costs", "記録された全費用の合計",
                "DAILY PROFIT", "日次利益",
                "Mod calculation", "Mod計算",
                "BALANCE", "残高",
                "Account balance after the day", "一日終了後の口座残高",
                "STORE", "店舗",
                "View", "表示",
                "Store results over time", "店舗実績の推移",
                "Product results over time", "商品実績の推移",
                "Total customers", "顧客合計",
                "Satisfied customers", "満足した顧客",
                "Satisfaction rate", "満足率",
                "Products not found", "見つからなかった商品",
                "Products too expensive", "高すぎる商品",
                "Incorrect change", "お釣りミス",
                "Harmed customers", "被害を受けた顧客",
                "Vending income", "自販機収入",
                "Loan income", "ローン収入",
                "Supply costs", "仕入れ費用",
                "Staff payment", "人件費",
                "Paint costs", "塗装費",
                "Floor costs", "床費用",
                "pts", "pt",
                "Latest value", "最新値",
                "Weighted average", "加重平均",
                "Total", "合計",
                "No saved daily summaries.", "保存された日次集計はありません。",
                "SUMMARY", "集計");

            SetDailySummaryTerms("ko",
                "NO SUMMARY", "요약 없음",
                "The summary will appear after the day is finished.", "하루가 끝나면 요약이 표시됩니다.",
                "CUSTOMERS", "고객",
                "Satisfied", "만족",
                "SATISFACTION", "만족도",
                "PRODUCT ISSUES", "상품 문제",
                "Not found", "찾지 못함",
                "Too expensive", "너무 비쌈",
                "SERVICE ISSUES", "서비스 문제",
                "Short change", "거스름돈 오류",
                "Harmed", "피해",
                "STORE POINTS", "매장 포인트",
                "Points earned that day", "그날 획득한 포인트",
                "CHECKOUT INCOME", "계산대 수입",
                "Checkout sales", "계산대 판매",
                "OTHER INCOME", "기타 수입",
                "Vending", "자판기",
                "Loans", "대출",
                "TOTAL INCOME", "총수입",
                "Checkout + vending + loans", "계산대 + 자판기 + 대출",
                "SUPPLIES", "물품 공급",
                "Cost of ordered stock", "주문 재고 비용",
                "STAFF", "직원",
                "Employee wages", "직원 급여",
                "RENT AND BILLS", "임대료 및 청구서",
                "Rent", "임대료",
                "Bills", "청구서",
                "INVESTMENTS", "투자",
                "Upgrades", "업그레이드",
                "Customization", "커스터마이징",
                "LOAN PAYMENT", "대출 상환",
                "Payment made that day", "그날 납부한 금액",
                "TOTAL EXPENSES", "총지출",
                "Sum of all recorded costs", "기록된 모든 비용의 합계",
                "DAILY PROFIT", "일일 이익",
                "Mod calculation", "모드 계산",
                "BALANCE", "잔액",
                "Account balance after the day", "하루 종료 후 계좌 잔액",
                "STORE", "매장",
                "View", "보기",
                "Store results over time", "시간별 매장 실적",
                "Product results over time", "시간별 상품 실적",
                "Total customers", "총 고객 수",
                "Satisfied customers", "만족 고객",
                "Satisfaction rate", "만족도",
                "Products not found", "찾지 못한 상품",
                "Products too expensive", "너무 비싼 상품",
                "Incorrect change", "거스름돈 오류",
                "Harmed customers", "피해 고객",
                "Vending income", "자판기 수입",
                "Loan income", "대출 수입",
                "Supply costs", "공급 비용",
                "Staff payment", "직원 비용",
                "Paint costs", "도색 비용",
                "Floor costs", "바닥 비용",
                "pts", "점",
                "Latest value", "최신 값",
                "Weighted average", "가중 평균",
                "Total", "합계",
                "No saved daily summaries.", "저장된 일일 요약이 없습니다.",
                "SUMMARY", "요약");

        }

        private static void AddDailySummaryTermsGroup4()
        {
            SetDailySummaryTerms("pt-PT",
                "NO SUMMARY", "Sem resumo",
                "The summary will appear after the day is finished.", "O resumo será apresentado após o fim do dia.",
                "CUSTOMERS", "Clientes",
                "Satisfied", "Satisfeitos",
                "SATISFACTION", "Satisfação",
                "PRODUCT ISSUES", "Problemas com produtos",
                "Not found", "Não encontrados",
                "Too expensive", "Demasiado caros",
                "SERVICE ISSUES", "Problemas de atendimento",
                "Short change", "Troco incorreto",
                "Harmed", "Prejudicados",
                "STORE POINTS", "Pontos da loja",
                "Points earned that day", "Pontos obtidos nesse dia",
                "CHECKOUT INCOME", "Receitas das caixas",
                "Checkout sales", "Vendas nas caixas",
                "OTHER INCOME", "Outras receitas",
                "Vending", "Máquinas de venda",
                "Loans", "Empréstimos",
                "TOTAL INCOME", "Receitas totais",
                "Checkout + vending + loans", "Caixas + máquinas + empréstimos",
                "SUPPLIES", "Abastecimento",
                "Cost of ordered stock", "Custo do stock encomendado",
                "STAFF", "Pessoal",
                "Employee wages", "Salários dos funcionários",
                "RENT AND BILLS", "Renda e faturas",
                "Rent", "Renda",
                "Bills", "Faturas",
                "INVESTMENTS", "Investimentos",
                "Upgrades", "Melhorias",
                "Customization", "Personalização",
                "LOAN PAYMENT", "Pagamento do empréstimo",
                "Payment made that day", "Pagamento efetuado nesse dia",
                "TOTAL EXPENSES", "Despesas totais",
                "Sum of all recorded costs", "Soma de todos os custos registados",
                "DAILY PROFIT", "Lucro diário",
                "Mod calculation", "Cálculo do mod",
                "BALANCE", "Saldo",
                "Account balance after the day", "Saldo da conta após o dia",
                "STORE", "Loja",
                "View", "Vista",
                "Store results over time", "Resultados da loja ao longo do tempo",
                "Product results over time", "Resultados do produto ao longo do tempo",
                "Total customers", "Total de clientes",
                "Satisfied customers", "Clientes satisfeitos",
                "Satisfaction rate", "Taxa de satisfação",
                "Products not found", "Produtos não encontrados",
                "Products too expensive", "Produtos demasiado caros",
                "Incorrect change", "Troco incorreto",
                "Harmed customers", "Clientes prejudicados",
                "Vending income", "Receitas das máquinas",
                "Loan income", "Receita do empréstimo",
                "Supply costs", "Custos de abastecimento",
                "Staff payment", "Custos de pessoal",
                "Paint costs", "Custos de pintura",
                "Floor costs", "Custos do piso",
                "pts", "pts",
                "Latest value", "Valor mais recente",
                "Weighted average", "Média ponderada",
                "Total", "Total",
                "No saved daily summaries.", "Não existem resumos diários guardados.",
                "SUMMARY", "Resumo");

            SetDailySummaryTerms("ru",
                "NO SUMMARY", "Нет сводки",
                "The summary will appear after the day is finished.", "Сводка появится после завершения дня.",
                "CUSTOMERS", "Клиенты",
                "Satisfied", "Довольны",
                "SATISFACTION", "Удовлетворённость",
                "PRODUCT ISSUES", "Проблемы с товарами",
                "Not found", "Не найдено",
                "Too expensive", "Слишком дорого",
                "SERVICE ISSUES", "Проблемы обслуживания",
                "Short change", "Неверная сдача",
                "Harmed", "Пострадали",
                "STORE POINTS", "Очки магазина",
                "Points earned that day", "Очки, полученные за этот день",
                "CHECKOUT INCOME", "Доход с касс",
                "Checkout sales", "Продажи на кассах",
                "OTHER INCOME", "Прочие доходы",
                "Vending", "Автоматы",
                "Loans", "Кредиты",
                "TOTAL INCOME", "Общий доход",
                "Checkout + vending + loans", "Кассы + автоматы + кредиты",
                "SUPPLIES", "Снабжение",
                "Cost of ordered stock", "Стоимость заказанного товара",
                "STAFF", "Персонал",
                "Employee wages", "Зарплаты сотрудников",
                "RENT AND BILLS", "Аренда и счета",
                "Rent", "Аренда",
                "Bills", "Счета",
                "INVESTMENTS", "Инвестиции",
                "Upgrades", "Улучшения",
                "Customization", "Оформление",
                "LOAN PAYMENT", "Платёж по кредиту",
                "Payment made that day", "Платёж за этот день",
                "TOTAL EXPENSES", "Общие расходы",
                "Sum of all recorded costs", "Сумма всех учтённых расходов",
                "DAILY PROFIT", "Прибыль за день",
                "Mod calculation", "Расчёт мода",
                "BALANCE", "Баланс",
                "Account balance after the day", "Баланс счёта после завершения дня",
                "STORE", "Магазин",
                "View", "Вид",
                "Store results over time", "Результаты магазина за период",
                "Product results over time", "Результаты товара за период",
                "Total customers", "Всего клиентов",
                "Satisfied customers", "Довольные клиенты",
                "Satisfaction rate", "Уровень удовлетворённости",
                "Products not found", "Товары не найдены",
                "Products too expensive", "Товары слишком дорогие",
                "Incorrect change", "Неверная сдача",
                "Harmed customers", "Пострадавшие клиенты",
                "Vending income", "Доход от автоматов",
                "Loan income", "Доход от кредита",
                "Supply costs", "Затраты на снабжение",
                "Staff payment", "Расходы на персонал",
                "Paint costs", "Расходы на покраску",
                "Floor costs", "Расходы на пол",
                "pts", "очк.",
                "Latest value", "Последнее значение",
                "Weighted average", "Средневзвешенное",
                "Total", "Итого",
                "No saved daily summaries.", "Нет сохранённых сводок по дням.",
                "SUMMARY", "Сводка");

            SetDailySummaryTerms("tr",
                "NO SUMMARY", "Özet yok",
                "The summary will appear after the day is finished.", "Özet, gün tamamlandıktan sonra görünecek.",
                "CUSTOMERS", "Müşteriler",
                "Satisfied", "Memnun",
                "SATISFACTION", "Memnuniyet",
                "PRODUCT ISSUES", "Ürün sorunları",
                "Not found", "Bulunamadı",
                "Too expensive", "Çok pahalı",
                "SERVICE ISSUES", "Hizmet sorunları",
                "Short change", "Yanlış para üstü",
                "Harmed", "Zarar gören",
                "STORE POINTS", "Mağaza puanları",
                "Points earned that day", "O gün kazanılan puanlar",
                "CHECKOUT INCOME", "Kasa geliri",
                "Checkout sales", "Kasa satışları",
                "OTHER INCOME", "Diğer gelirler",
                "Vending", "Otomatlar",
                "Loans", "Krediler",
                "TOTAL INCOME", "Toplam gelir",
                "Checkout + vending + loans", "Kasa + otomatlar + krediler",
                "SUPPLIES", "Tedarik",
                "Cost of ordered stock", "Sipariş edilen stok maliyeti",
                "STAFF", "Personel",
                "Employee wages", "Çalışan ücretleri",
                "RENT AND BILLS", "Kira ve faturalar",
                "Rent", "Kira",
                "Bills", "Faturalar",
                "INVESTMENTS", "Yatırımlar",
                "Upgrades", "Yükseltmeler",
                "Customization", "Özelleştirme",
                "LOAN PAYMENT", "Kredi ödemesi",
                "Payment made that day", "O gün yapılan ödeme",
                "TOTAL EXPENSES", "Toplam giderler",
                "Sum of all recorded costs", "Kaydedilen tüm maliyetlerin toplamı",
                "DAILY PROFIT", "Günlük kâr",
                "Mod calculation", "Mod hesaplaması",
                "BALANCE", "Bakiye",
                "Account balance after the day", "Gün sonundaki hesap bakiyesi",
                "STORE", "Mağaza",
                "View", "Görünüm",
                "Store results over time", "Zaman içinde mağaza sonuçları",
                "Product results over time", "Zaman içinde ürün sonuçları",
                "Total customers", "Toplam müşteri",
                "Satisfied customers", "Memnun müşteriler",
                "Satisfaction rate", "Memnuniyet oranı",
                "Products not found", "Bulunamayan ürünler",
                "Products too expensive", "Çok pahalı ürünler",
                "Incorrect change", "Yanlış para üstü",
                "Harmed customers", "Zarar gören müşteriler",
                "Vending income", "Otomat geliri",
                "Loan income", "Kredi geliri",
                "Supply costs", "Tedarik maliyetleri",
                "Staff payment", "Personel ödemesi",
                "Paint costs", "Boya maliyetleri",
                "Floor costs", "Zemin maliyetleri",
                "pts", "puan",
                "Latest value", "Son değer",
                "Weighted average", "Ağırlıklı ortalama",
                "Total", "Toplam",
                "No saved daily summaries.", "Kaydedilmiş günlük özet yok.",
                "SUMMARY", "Özet");

        }

        private static void AddDailySummaryTermsGroup5()
        {
            SetDailySummaryTerms("da",
                "NO SUMMARY", "Ingen oversigt",
                "The summary will appear after the day is finished.", "Oversigten vises, når dagen er afsluttet.",
                "CUSTOMERS", "Kunder",
                "Satisfied", "Tilfredse",
                "SATISFACTION", "Tilfredshed",
                "PRODUCT ISSUES", "Produktproblemer",
                "Not found", "Ikke fundet",
                "Too expensive", "For dyrt",
                "SERVICE ISSUES", "Serviceproblemer",
                "Short change", "Forkert byttepenge",
                "Harmed", "Berørte",
                "STORE POINTS", "Butikspoint",
                "Points earned that day", "Point optjent den dag",
                "CHECKOUT INCOME", "Kasseindtægt",
                "Checkout sales", "Salg ved kasserne",
                "OTHER INCOME", "Andre indtægter",
                "Vending", "Automater",
                "Loans", "Lån",
                "TOTAL INCOME", "Samlet indtægt",
                "Checkout + vending + loans", "Kasser + automater + lån",
                "SUPPLIES", "Vareindkøb",
                "Cost of ordered stock", "Pris på bestilte varer",
                "STAFF", "Personale",
                "Employee wages", "Medarbejderlønninger",
                "RENT AND BILLS", "Husleje og regninger",
                "Rent", "Husleje",
                "Bills", "Regninger",
                "INVESTMENTS", "Investeringer",
                "Upgrades", "Opgraderinger",
                "Customization", "Tilpasning",
                "LOAN PAYMENT", "Afdrag på lån",
                "Payment made that day", "Betaling foretaget den dag",
                "TOTAL EXPENSES", "Samlede udgifter",
                "Sum of all recorded costs", "Summen af alle registrerede omkostninger",
                "DAILY PROFIT", "Dagens overskud",
                "Mod calculation", "Modberegning",
                "BALANCE", "Saldo",
                "Account balance after the day", "Kontosaldo efter dagen",
                "STORE", "Butik",
                "View", "Visning",
                "Store results over time", "Butikkens resultater over tid",
                "Product results over time", "Produktets resultater over tid",
                "Total customers", "Kunder i alt",
                "Satisfied customers", "Tilfredse kunder",
                "Satisfaction rate", "Tilfredshedsgrad",
                "Products not found", "Produkter ikke fundet",
                "Products too expensive", "Produkter for dyre",
                "Incorrect change", "Forkert byttepenge",
                "Harmed customers", "Berørte kunder",
                "Vending income", "Automatindtægt",
                "Loan income", "Låneindtægt",
                "Supply costs", "Vareindkøbsomkostninger",
                "Staff payment", "Personaleudgifter",
                "Paint costs", "Malingsomkostninger",
                "Floor costs", "Gulvomkostninger",
                "pts", "point",
                "Latest value", "Seneste værdi",
                "Weighted average", "Vægtet gennemsnit",
                "Total", "I alt",
                "No saved daily summaries.", "Ingen gemte dagsoversigter.",
                "SUMMARY", "Oversigt");

            SetDailySummaryTerms("fi",
                "NO SUMMARY", "Ei yhteenvetoa",
                "The summary will appear after the day is finished.", "Yhteenveto tulee näkyviin päivän päätyttyä.",
                "CUSTOMERS", "Asiakkaat",
                "Satisfied", "Tyytyväiset",
                "SATISFACTION", "Tyytyväisyys",
                "PRODUCT ISSUES", "Tuoteongelmat",
                "Not found", "Ei löytynyt",
                "Too expensive", "Liian kallis",
                "SERVICE ISSUES", "Palveluongelmat",
                "Short change", "Väärä vaihtoraha",
                "Harmed", "Haittaa kärsineet",
                "STORE POINTS", "Kaupan pisteet",
                "Points earned that day", "Sinä päivänä saadut pisteet",
                "CHECKOUT INCOME", "Kassatulot",
                "Checkout sales", "Kassamyynti",
                "OTHER INCOME", "Muut tulot",
                "Vending", "Myyntiautomaatit",
                "Loans", "Lainat",
                "TOTAL INCOME", "Tulot yhteensä",
                "Checkout + vending + loans", "Kassat + automaatit + lainat",
                "SUPPLIES", "Täydennystilaukset",
                "Cost of ordered stock", "Tilatun varaston kustannus",
                "STAFF", "Henkilöstö",
                "Employee wages", "Työntekijöiden palkat",
                "RENT AND BILLS", "Vuokra ja laskut",
                "Rent", "Vuokra",
                "Bills", "Laskut",
                "INVESTMENTS", "Investoinnit",
                "Upgrades", "Päivitykset",
                "Customization", "Mukautukset",
                "LOAN PAYMENT", "Lainanlyhennys",
                "Payment made that day", "Sinä päivänä suoritettu maksu",
                "TOTAL EXPENSES", "Menot yhteensä",
                "Sum of all recorded costs", "Kaikkien kirjattujen kustannusten summa",
                "DAILY PROFIT", "Päivän voitto",
                "Mod calculation", "Modin laskelma",
                "BALANCE", "Saldo",
                "Account balance after the day", "Tilin saldo päivän jälkeen",
                "STORE", "Kauppa",
                "View", "Näkymä",
                "Store results over time", "Kaupan tulokset ajan mittaan",
                "Product results over time", "Tuotteen tulokset ajan mittaan",
                "Total customers", "Asiakkaita yhteensä",
                "Satisfied customers", "Tyytyväiset asiakkaat",
                "Satisfaction rate", "Tyytyväisyysaste",
                "Products not found", "Tuotteita ei löytynyt",
                "Products too expensive", "Tuotteet liian kalliita",
                "Incorrect change", "Väärä vaihtoraha",
                "Harmed customers", "Haittaa kärsineet asiakkaat",
                "Vending income", "Automaattitulot",
                "Loan income", "Lainatulot",
                "Supply costs", "Täydennyskustannukset",
                "Staff payment", "Henkilöstökulut",
                "Paint costs", "Maalauskulut",
                "Floor costs", "Lattiakulut",
                "pts", "p",
                "Latest value", "Viimeisin arvo",
                "Weighted average", "Painotettu keskiarvo",
                "Total", "Yhteensä",
                "No saved daily summaries.", "Ei tallennettuja päiväyhteenvetoja.",
                "SUMMARY", "Yhteenveto");

            SetDailySummaryTerms("hu",
                "NO SUMMARY", "Nincs összefoglaló",
                "The summary will appear after the day is finished.", "Az összefoglaló a nap befejezése után jelenik meg.",
                "CUSTOMERS", "Vásárlók",
                "Satisfied", "Elégedettek",
                "SATISFACTION", "Elégedettség",
                "PRODUCT ISSUES", "Termékproblémák",
                "Not found", "Nem találták",
                "Too expensive", "Túl drága",
                "SERVICE ISSUES", "Kiszolgálási problémák",
                "Short change", "Hibás visszajáró",
                "Harmed", "Károsultak",
                "STORE POINTS", "Bolt pontjai",
                "Points earned that day", "Aznap szerzett pontok",
                "CHECKOUT INCOME", "Pénztári bevétel",
                "Checkout sales", "Pénztári eladások",
                "OTHER INCOME", "Egyéb bevételek",
                "Vending", "Automaták",
                "Loans", "Hitelek",
                "TOTAL INCOME", "Összes bevétel",
                "Checkout + vending + loans", "Pénztár + automaták + hitelek",
                "SUPPLIES", "Árubeszerzés",
                "Cost of ordered stock", "A megrendelt készlet költsége",
                "STAFF", "Személyzet",
                "Employee wages", "Alkalmazotti bérek",
                "RENT AND BILLS", "Bérleti díj és számlák",
                "Rent", "Bérleti díj",
                "Bills", "Számlák",
                "INVESTMENTS", "Befektetések",
                "Upgrades", "Fejlesztések",
                "Customization", "Testreszabás",
                "LOAN PAYMENT", "Hiteltörlesztés",
                "Payment made that day", "Aznap teljesített fizetés",
                "TOTAL EXPENSES", "Összes kiadás",
                "Sum of all recorded costs", "Az összes rögzített költség összege",
                "DAILY PROFIT", "Napi nyereség",
                "Mod calculation", "Mod számítása",
                "BALANCE", "Egyenleg",
                "Account balance after the day", "A számla egyenlege a nap végén",
                "STORE", "Bolt",
                "View", "Nézet",
                "Store results over time", "A bolt eredményei időben",
                "Product results over time", "A termék eredményei időben",
                "Total customers", "Vásárlók összesen",
                "Satisfied customers", "Elégedett vásárlók",
                "Satisfaction rate", "Elégedettségi arány",
                "Products not found", "Nem talált termékek",
                "Products too expensive", "Túl drága termékek",
                "Incorrect change", "Hibás visszajáró",
                "Harmed customers", "Károsult vásárlók",
                "Vending income", "Automaták bevétele",
                "Loan income", "Hitelbevétel",
                "Supply costs", "Beszerzési költségek",
                "Staff payment", "Személyzeti költségek",
                "Paint costs", "Festési költségek",
                "Floor costs", "Padlóköltségek",
                "pts", "pont",
                "Latest value", "Legutóbbi érték",
                "Weighted average", "Súlyozott átlag",
                "Total", "Összesen",
                "No saved daily summaries.", "Nincs mentett napi összefoglaló.",
                "SUMMARY", "Összefoglaló");

        }

        private static void AddDailySummaryTermsGroup6()
        {
            SetDailySummaryTerms("ro",
                "NO SUMMARY", "Fără rezumat",
                "The summary will appear after the day is finished.", "Rezumatul va apărea după încheierea zilei.",
                "CUSTOMERS", "Clienți",
                "Satisfied", "Mulțumiți",
                "SATISFACTION", "Satisfacție",
                "PRODUCT ISSUES", "Probleme cu produsele",
                "Not found", "Negăsite",
                "Too expensive", "Prea scumpe",
                "SERVICE ISSUES", "Probleme de servire",
                "Short change", "Rest incorect",
                "Harmed", "Prejudiciați",
                "STORE POINTS", "Puncte magazin",
                "Points earned that day", "Puncte obținute în acea zi",
                "CHECKOUT INCOME", "Venit la case",
                "Checkout sales", "Vânzări la case",
                "OTHER INCOME", "Alte venituri",
                "Vending", "Automate",
                "Loans", "Împrumuturi",
                "TOTAL INCOME", "Venit total",
                "Checkout + vending + loans", "Case + automate + împrumuturi",
                "SUPPLIES", "Aprovizionare",
                "Cost of ordered stock", "Costul stocului comandat",
                "STAFF", "Personal",
                "Employee wages", "Salariile angajaților",
                "RENT AND BILLS", "Chirie și facturi",
                "Rent", "Chirie",
                "Bills", "Facturi",
                "INVESTMENTS", "Investiții",
                "Upgrades", "Îmbunătățiri",
                "Customization", "Personalizare",
                "LOAN PAYMENT", "Plata împrumutului",
                "Payment made that day", "Plată efectuată în acea zi",
                "TOTAL EXPENSES", "Cheltuieli totale",
                "Sum of all recorded costs", "Suma tuturor costurilor înregistrate",
                "DAILY PROFIT", "Profit zilnic",
                "Mod calculation", "Calculul modului",
                "BALANCE", "Sold",
                "Account balance after the day", "Soldul contului după încheierea zilei",
                "STORE", "Magazin",
                "View", "Vizualizare",
                "Store results over time", "Rezultatele magazinului în timp",
                "Product results over time", "Rezultatele produsului în timp",
                "Total customers", "Total clienți",
                "Satisfied customers", "Clienți mulțumiți",
                "Satisfaction rate", "Rata satisfacției",
                "Products not found", "Produse negăsite",
                "Products too expensive", "Produse prea scumpe",
                "Incorrect change", "Rest incorect",
                "Harmed customers", "Clienți prejudiciați",
                "Vending income", "Venit din automate",
                "Loan income", "Venit din împrumut",
                "Supply costs", "Costuri de aprovizionare",
                "Staff payment", "Costuri de personal",
                "Paint costs", "Costuri de vopsire",
                "Floor costs", "Costuri pentru podea",
                "pts", "pct.",
                "Latest value", "Ultima valoare",
                "Weighted average", "Media ponderată",
                "Total", "Total",
                "No saved daily summaries.", "Nu există rezumate zilnice salvate.",
                "SUMMARY", "Rezumat");

            SetDailySummaryTerms("cs",
                "NO SUMMARY", "Žádné shrnutí",
                "The summary will appear after the day is finished.", "Shrnutí se zobrazí po dokončení dne.",
                "CUSTOMERS", "Zákazníci",
                "Satisfied", "Spokojení",
                "SATISFACTION", "Spokojenost",
                "PRODUCT ISSUES", "Problémy s produkty",
                "Not found", "Nenalezeno",
                "Too expensive", "Příliš drahé",
                "SERVICE ISSUES", "Problémy obsluhy",
                "Short change", "Nesprávné vrácení",
                "Harmed", "Poškození",
                "STORE POINTS", "Body obchodu",
                "Points earned that day", "Body získané za daný den",
                "CHECKOUT INCOME", "Příjem z pokladen",
                "Checkout sales", "Prodej u pokladen",
                "OTHER INCOME", "Ostatní příjmy",
                "Vending", "Automaty",
                "Loans", "Půjčky",
                "TOTAL INCOME", "Celkové příjmy",
                "Checkout + vending + loans", "Pokladny + automaty + půjčky",
                "SUPPLIES", "Zásobování",
                "Cost of ordered stock", "Cena objednaného zboží",
                "STAFF", "Personál",
                "Employee wages", "Mzdy zaměstnanců",
                "RENT AND BILLS", "Nájem a účty",
                "Rent", "Nájem",
                "Bills", "Účty",
                "INVESTMENTS", "Investice",
                "Upgrades", "Vylepšení",
                "Customization", "Přizpůsobení",
                "LOAN PAYMENT", "Splátka půjčky",
                "Payment made that day", "Platba provedená daný den",
                "TOTAL EXPENSES", "Celkové výdaje",
                "Sum of all recorded costs", "Součet všech zaznamenaných nákladů",
                "DAILY PROFIT", "Denní zisk",
                "Mod calculation", "Výpočet modu",
                "BALANCE", "Zůstatek",
                "Account balance after the day", "Zůstatek účtu po skončení dne",
                "STORE", "Obchod",
                "View", "Zobrazení",
                "Store results over time", "Výsledky obchodu v čase",
                "Product results over time", "Výsledky produktu v čase",
                "Total customers", "Celkem zákazníků",
                "Satisfied customers", "Spokojení zákazníci",
                "Satisfaction rate", "Míra spokojenosti",
                "Products not found", "Nenalezené produkty",
                "Products too expensive", "Příliš drahé produkty",
                "Incorrect change", "Nesprávné vrácení",
                "Harmed customers", "Poškození zákazníci",
                "Vending income", "Příjmy z automatů",
                "Loan income", "Příjem z půjčky",
                "Supply costs", "Náklady na zásobování",
                "Staff payment", "Náklady na personál",
                "Paint costs", "Náklady na malování",
                "Floor costs", "Náklady na podlahu",
                "pts", "b.",
                "Latest value", "Nejnovější hodnota",
                "Weighted average", "Vážený průměr",
                "Total", "Celkem",
                "No saved daily summaries.", "Žádná uložená denní shrnutí.",
                "SUMMARY", "Shrnutí");

            SetDailySummaryTerms("lt",
                "NO SUMMARY", "Nėra suvestinės",
                "The summary will appear after the day is finished.", "Suvestinė bus rodoma pasibaigus dienai.",
                "CUSTOMERS", "Klientai",
                "Satisfied", "Patenkinti",
                "SATISFACTION", "Pasitenkinimas",
                "PRODUCT ISSUES", "Prekių problemos",
                "Not found", "Nerasta",
                "Too expensive", "Per brangu",
                "SERVICE ISSUES", "Aptarnavimo problemos",
                "Short change", "Neteisinga grąža",
                "Harmed", "Nukentėjo",
                "STORE POINTS", "Parduotuvės taškai",
                "Points earned that day", "Tą dieną gauti taškai",
                "CHECKOUT INCOME", "Kasų pajamos",
                "Checkout sales", "Pardavimai kasose",
                "OTHER INCOME", "Kitos pajamos",
                "Vending", "Automatai",
                "Loans", "Paskolos",
                "TOTAL INCOME", "Bendros pajamos",
                "Checkout + vending + loans", "Kasos + automatai + paskolos",
                "SUPPLIES", "Tiekimas",
                "Cost of ordered stock", "Užsakytų atsargų kaina",
                "STAFF", "Personalas",
                "Employee wages", "Darbuotojų atlyginimai",
                "RENT AND BILLS", "Nuoma ir sąskaitos",
                "Rent", "Nuoma",
                "Bills", "Sąskaitos",
                "INVESTMENTS", "Investicijos",
                "Upgrades", "Patobulinimai",
                "Customization", "Pritaikymas",
                "LOAN PAYMENT", "Paskolos įmoka",
                "Payment made that day", "Tą dieną atliktas mokėjimas",
                "TOTAL EXPENSES", "Bendros išlaidos",
                "Sum of all recorded costs", "Visų užregistruotų sąnaudų suma",
                "DAILY PROFIT", "Dienos pelnas",
                "Mod calculation", "Modifikacijos skaičiavimas",
                "BALANCE", "Balansas",
                "Account balance after the day", "Sąskaitos balansas po dienos",
                "STORE", "Parduotuvė",
                "View", "Rodinys",
                "Store results over time", "Parduotuvės rezultatai laikui bėgant",
                "Product results over time", "Produkto rezultatai laikui bėgant",
                "Total customers", "Iš viso klientų",
                "Satisfied customers", "Patenkinti klientai",
                "Satisfaction rate", "Pasitenkinimo lygis",
                "Products not found", "Nerastos prekės",
                "Products too expensive", "Per brangios prekės",
                "Incorrect change", "Neteisinga grąža",
                "Harmed customers", "Nukentėję klientai",
                "Vending income", "Automatų pajamos",
                "Loan income", "Paskolos pajamos",
                "Supply costs", "Tiekimo išlaidos",
                "Staff payment", "Personalo išlaidos",
                "Paint costs", "Dažymo išlaidos",
                "Floor costs", "Grindų išlaidos",
                "pts", "tšk.",
                "Latest value", "Naujausia reikšmė",
                "Weighted average", "Svertinis vidurkis",
                "Total", "Iš viso",
                "No saved daily summaries.", "Nėra išsaugotų dienos suvestinių.",
                "SUMMARY", "Suvestinė");

        }

        private static void SetDailySummaryTerms(string code, params string[] pairs)
        {
            if (!Packs.TryGetValue(code, out LanguagePack pack) || pairs == null) return;

            for (int i = 0; i + 1 < pairs.Length; i += 2)
                pack.Terms[pairs[i]] = pairs[i + 1];
        }
    }
}
