using System;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.EventSystems;

namespace StatisticMod
{
    /// <summary>
    /// Centralny katalog tooltipów dla wszystkich ekranów statystyk.
    /// Używa istniejącego popupu ProductInfoTooltip z StatsAppManager,
    /// dzięki czemu wygląd i zachowanie pozostają spójne w całym modzie.
    /// </summary>
    public partial class StatsAppManager
    {
        private Transform BeginMetricTooltipRoot(TextMeshProUGUI tmp, string rootName)
        {
            if (tmp == null) return null;

            Transform old = tmp.transform.Find(rootName);
            if (old != null)
                UnityEngine.Object.Destroy(old.gameObject);

            var root = new GameObject(rootName);
            root.transform.SetParent(tmp.transform, false);

            RectTransform rt = root.AddComponent<RectTransform>();
            rt.anchorMin = Vector2.zero;
            rt.anchorMax = Vector2.one;
            rt.offsetMin = Vector2.zero;
            rt.offsetMax = Vector2.zero;
            return root.transform;
        }

        private void CreateMetricLineZone(
            Transform root,
            RectTransform tileRT,
            string name,
            int lineIndex,
            int lineCount,
            float xMin,
            float xMax,
            string title,
            string body)
        {
            if (root == null || lineCount <= 0 || lineIndex < 0 || lineIndex >= lineCount) return;

            float yMax = 1f - lineIndex / (float)lineCount;
            float yMin = 1f - (lineIndex + 1) / (float)lineCount;

            CreateProductInfoTooltipZone(
                root,
                tileRT,
                name,
                new Vector2(Mathf.Clamp01(xMin), yMin),
                new Vector2(Mathf.Clamp01(xMax), yMax),
                title,
                body);
        }

        private void AttachStatsInfoTooltipZones(Transform tile, TextMeshProUGUI infoTmp)
        {
            if (tile == null || infoTmp == null) return;

            Transform root = BeginMetricTooltipRoot(infoTmp, "StatsMetricTooltipZones");
            if (root == null) return;

            RectTransform tileRT = tile.GetComponent<RectTransform>();
            bool expiryEnabled = SmartExpiration.PluginConfig.ExpiryEnabled;
            int lines = expiryEnabled ? 6 : 4;

            CreateMetricLineZone(root, tileRT, "Sold", 0, lines, 0.00f, 0.45f,
                Plugin.T("Sprzedane", "Sold"),
                Plugin.T(
                    "Ilość produktu faktycznie sprzedana w wybranym dniu. Produkty ważone są pokazywane w kilogramach.",
                    "Quantity actually sold on the selected day. Weighted products are shown in kilograms."));

            CreateMetricLineZone(root, tileRT, "Revenue", 1, lines, 0.00f, 0.45f,
                Plugin.T("Przychód", "Revenue"),
                Plugin.T(
                    "Łączna wartość sprzedaży tego produktu zapisana przez tracker sprzedaży dla wybranego dnia.",
                    "Total sales value recorded by the sales tracker for this product on the selected day."));

            CreateMetricLineZone(root, tileRT, "SalesTrend", 2, lines, 0.00f, 0.45f,
                Plugin.T("Trend sprzedaży", "Sales trend"),
                Plugin.T(
                    "Zmiana sprzedanej ilości względem poprzedniego dnia: (dzisiaj - poprzedni dzień) / poprzedni dzień. Gdy brak danych bazowych, wyświetlane jest —.",
                    "Change in sold quantity versus the previous day: (today - previous day) / previous day. If there is no valid baseline, — is shown."));

            CreateMetricLineZone(root, tileRT, "RevenueShare", 3, lines, 0.00f, 0.45f,
                Plugin.T("Udział w przychodzie", "Revenue share"),
                Plugin.T(
                    "Procent całego dziennego przychodu ze sprzedaży przypadający na ten produkt.",
                    "Percentage of total daily sales revenue generated by this product."));

            if (expiryEnabled)
            {
                CreateMetricLineZone(root, tileRT, "Wasted", 4, lines, 0.00f, 0.45f,
                    Plugin.T("Wyrzucone", "Wasted"),
                    Plugin.T(
                        "Ilość produktu zarejestrowana przez mod jako wyrzucona/utracona. Produkty ważone są pokazywane w kilogramach.",
                        "Quantity recorded by the mod as discarded/lost. Weighted products are shown in kilograms."));

                CreateMetricLineZone(root, tileRT, "WasteLoss", 5, lines, 0.00f, 0.45f,
                    Plugin.T("Strata", "Loss"),
                    Plugin.T(
                        "Wartość wyrzuconego towaru liczona jako koszt zakupu utraconych sztuk lub kilogramów.",
                        "Value of discarded stock calculated from the purchase cost of the lost units or kilograms."));
            }
        }

        private void AttachProfitabilityInfoTooltipZones(Transform tile, TextMeshProUGUI infoTmp)
        {
            if (tile == null || infoTmp == null) return;
            Transform root = BeginMetricTooltipRoot(infoTmp, "ProfitMetricTooltipZones");
            if (root == null) return;
            RectTransform tileRT = tile.GetComponent<RectTransform>();

            CreateMetricLineZone(root, tileRT, "Revenue", 0, 4, 0.00f, 0.58f,
                Plugin.T("Przychód", "Revenue"),
                Plugin.T(
                    "Łączny przychód ze sprzedaży produktu w wybranym dniu.",
                    "Total revenue from sales of this product on the selected day."));

            CreateMetricLineZone(root, tileRT, "Cost", 1, 4, 0.00f, 0.58f,
                Plugin.T("Koszt sprzedanego towaru", "Cost of goods sold"),
                Plugin.T(
                    "Koszt zakupowy sprzedanych sztuk zapisany w chwili sprzedaży. Jeśli historycznie koszt nie był śledzony, mod pokazuje — zamiast zgadywać.",
                    "Purchase cost of sold units captured at the time of sale. If historical cost was not tracked, the mod shows — instead of guessing."));

            CreateMetricLineZone(root, tileRT, "GrossProfit", 2, 4, 0.00f, 0.64f,
                Plugin.T("Zysk brutto", "Gross profit"),
                Plugin.T(
                    "Przychód minus koszt sprzedanego towaru (COGS). Nie odejmuje czynszu, wynagrodzeń ani innych kosztów sklepu.",
                    "Revenue minus cost of goods sold (COGS). It does not subtract rent, wages, or other store expenses."));

            CreateMetricLineZone(root, tileRT, "Margin", 3, 4, 0.00f, 0.48f,
                Plugin.T("Marża brutto", "Gross margin"),
                Plugin.T(
                    "Zysk brutto / przychód × 100%. Pokazuje, jaka część przychodu pozostaje po odjęciu kosztu sprzedanego towaru.",
                    "Gross profit / revenue × 100%. Shows how much of revenue remains after cost of goods sold."));
        }

        private void AttachAnalysisInfoTooltipZones(Transform tile, TextMeshProUGUI infoTmp)
        {
            if (tile == null || infoTmp == null) return;
            Transform root = BeginMetricTooltipRoot(infoTmp, "AnalysisMetricTooltipZones");
            if (root == null) return;
            RectTransform tileRT = tile.GetComponent<RectTransform>();

            switch (_analysisView)
            {
                case AnalysisViewMode.Demand:
                    CreateMetricLineZone(root, tileRT, "Demand", 0, 5, 0.00f, 0.24f,
                        Plugin.T("Popyt", "Demand"),
                        Plugin.T("Łączna ilość, której klienci chcieli w wybranym zakresie dni. Obejmuje również popyt niezrealizowany.", "Total quantity customers wanted during the selected day range. It also includes unfulfilled demand."));
                    CreateMetricLineZone(root, tileRT, "Sold", 0, 5, 0.50f, 0.74f,
                        Plugin.T("Sprz. = Sprzedane", "Sold"),
                        Plugin.T("Ilość faktycznie sprzedana klientom w wybranym zakresie dni.", "Quantity actually sold to customers during the selected day range."));
                    CreateMetricLineZone(root, tileRT, "Picked", 1, 5, 0.00f, 0.24f,
                        Plugin.T("Zebr. = Zebrane", "Picked"),
                        Plugin.T("Ilość, którą klienci znaleźli i zabrali z ekspozycji. To etap realizacji popytu przed finalną sprzedażą.", "Quantity customers found and picked from displays. This is the demand-fulfilment stage before the final sale."));
                    CreateMetricLineZone(root, tileRT, "Availability", 1, 5, 0.50f, 0.76f,
                        Plugin.T("Dost. = Dostępność", "Avail. = Availability"),
                        Plugin.T("Poziom obsługi = Zebrane / Popyt. 100% oznacza, że cały zgłoszony popyt został pokryty.", "Service level = Picked / Demand. 100% means all recorded demand was fulfilled."));
                    CreateMetricLineZone(root, tileRT, "Average", 2, 5, 0.00f, 0.19f,
                        Plugin.T("Śr. = Średnia dzienna", "Avg. = Daily average"),
                        Plugin.T("Średni dzienny popyt w aktualnie wybranym zakresie, np. 7 dni.", "Average daily demand in the currently selected range, for example 7 days."));
                    CreateMetricLineZone(root, tileRT, "Last3", 2, 5, 0.44f, 0.72f,
                        Plugin.T("Ost.3 = Ostatnie 3 dni", "Last 3 days"),
                        Plugin.T("Średni popyt z ostatnich 3 zakończonych dni sprzedażowych.", "Average demand from the last 3 completed sales days."));
                    CreateMetricLineZone(root, tileRT, "Previous3", 3, 5, 0.00f, 0.34f,
                        Plugin.T("Poprz.3 = Poprzednie 3 dni", "Prev. 3 days"),
                        Plugin.T("Średni popyt z 3 dni bezpośrednio poprzedzających ostatnie 3 zakończone dni.", "Average demand from the 3 days immediately preceding the last 3 completed days."));
                    CreateMetricLineZone(root, tileRT, "Trend", 3, 5, 0.46f, 0.74f,
                        Plugin.T("Trend popytu", "Demand trend"),
                        Plugin.T("Zmiana między Ost.3 i Poprz.3: (Ost.3 - Poprz.3) / Poprz.3. ↑ od +10%, ↓ od -10%, → pomiędzy.", "Change between Last 3 and Prev. 3: (Last 3 - Prev. 3) / Prev. 3. ↑ from +10%, ↓ from -10%, → in between."));
                    CreateMetricLineZone(root, tileRT, "Forecast", 4, 5, 0.00f, 0.26f,
                        Plugin.T("Prog. = Prognoza popytu", "Fcst. = Demand forecast"),
                        Plugin.T("Prognoza dzienna = 65% średniej z ostatnich 3 dni + 35% średniej z ostatnich 14 dni. Druga wartość pokazuje prognozę na 3 dni.", "Daily forecast = 65% of the last-3-day average + 35% of the last-14-day average. The second value is the 3-day forecast."));
                    break;

                case AnalysisViewMode.MissedSales:
                    CreateMetricLineZone(root, tileRT, "StockMiss", 0, 4, 0.00f, 0.38f,
                        Plugin.T("Brak zapasu", "Stock miss"),
                        Plugin.T("Łączna niezrealizowana ilość z powodów magazynowych: brak wszędzie, pusta półka lub produkt niewystawiony. Kwota obok to oszacowany utracony przychód tylko z tych realnych braków.", "Total unfulfilled quantity caused by stock/display issues: globally out of stock, empty shelf, or not displayed. The amount beside it is estimated lost revenue from these real misses only."));
                    CreateMetricLineZone(root, tileRT, "GlobalOOS", 1, 4, 0.00f, 0.42f,
                        Plugin.T("Brak wszędzie", "Out of stock"),
                        Plugin.T("Klient chciał produkt, ale nie było dostępnego zapasu ani w sklepie, ani w magazynie.", "Customer wanted the product, but there was no available stock in either the shop or warehouse."));
                    CreateMetricLineZone(root, tileRT, "ShelfEmpty", 2, 4, 0.00f, 0.38f,
                        Plugin.T("Pusta półka", "Empty shelf"),
                        Plugin.T("Klient nie mógł pobrać produktu z ekspozycji, mimo że problem został sklasyfikowany jako pusta półka.", "Customer could not pick the product from the display because the issue was classified as an empty shelf."));
                    CreateMetricLineZone(root, tileRT, "NotDisplayed", 2, 4, 0.58f, 0.88f,
                        Plugin.T("Niewyst. = Niewystawiony", "Not shown = Not displayed"),
                        Plugin.T("Produkt był na liście zakupów klienta, ale nie był wystawiony na dostępnej ekspozycji.", "Product was on the customer's shopping list but was not placed on an available display."));
                    CreateMetricLineZone(root, tileRT, "OtherUnfulfilled", 3, 4, 0.00f, 0.72f,
                        Plugin.T("Inne (bez straty)", "Other (no lost revenue)"),
                        Plugin.T("Niezrealizowana część popytu, której mod nie przypisał do realnego braku magazynowego. Nie zwiększa oszacowanej utraconej sprzedaży.", "Unfulfilled demand that the mod did not classify as a real stock/display shortage. It does not increase estimated lost sales."));
                    break;

                case AnalysisViewMode.Restock:
                    CreateMetricLineZone(root, tileRT, "Shop", 0, 4, 0.00f, 0.25f,
                        Plugin.T("Sklep", "Shop"),
                        Plugin.T("Aktualna ilość produktu znajdująca się w części sklepowej/na ekspozycjach.", "Current quantity of the product located in the shop/on displays."));
                    CreateMetricLineZone(root, tileRT, "Warehouse", 0, 4, 0.50f, 0.73f,
                        Plugin.T("Mag. = Magazyn", "Wh. = Warehouse"),
                        Plugin.T("Aktualna ilość produktu znajdująca się w magazynie.", "Current quantity of the product located in the warehouse."));
                    CreateMetricLineZone(root, tileRT, "Cover", 1, 4, 0.00f, 0.33f,
                        Plugin.T("Pokrycie zapasu", "Stock cover"),
                        Plugin.T("Szacowana liczba dni, na które wystarczy cały zapas: łączny stan / prognozowany dzienny popyt.", "Estimated number of days the total stock will last: total stock / forecast daily demand."));
                    CreateMetricLineZone(root, tileRT, "ToShelf", 2, 4, 0.00f, 0.38f,
                        Plugin.T("Na półkę", "To shelf"),
                        Plugin.T("Sugerowana ilość do przeniesienia z magazynu na ekspozycję, aby zbliżyć półkę do około 1,5 dnia prognozowanego popytu.", "Suggested quantity to move from warehouse to display, targeting roughly 1.5 days of forecast demand on the shelf."));
                    CreateMetricLineZone(root, tileRT, "Order", 3, 4, 0.00f, 0.34f,
                        Plugin.T("Zamów", "Order"),
                        Plugin.T("Sugerowane zamówienie do docelowego zapasu około 4 dni popytu. Dla produktów z terminem przydatności rekomendacja jest ograniczana, aby zmniejszyć ryzyko przeterminowania. Liczba w nawiasie to kartony.", "Suggested order targeting roughly 4 days of demand. For products with shelf life, the recommendation is capped to reduce expiry risk. The number in parentheses is boxes."));
                    break;

                case AnalysisViewMode.Pricing:
                    CreateMetricLineZone(root, tileRT, "Cost", 0, 4, 0.00f, 0.25f,
                        Plugin.T("Koszt", "Cost"),
                        Plugin.T("Aktualny koszt zakupu jednej jednostki produktu z PriceManager.CurrentCost.", "Current purchase cost per product unit from PriceManager.CurrentCost."));
                    CreateMetricLineZone(root, tileRT, "Price", 0, 4, 0.50f, 0.73f,
                        Plugin.T("Cena", "Price"),
                        Plugin.T("Aktualna cena sprzedaży ustawiona dla produktu.", "Current selling price set for the product."));
                    CreateMetricLineZone(root, tileRT, "Market", 1, 4, 0.00f, 0.34f,
                        Plugin.T("Rynkowa", "Market"),
                        Plugin.T("Cena rynkowa z danych Pricing. Jeśli jej brak, mod wylicza wartość orientacyjną z kosztu i optymalnej stopy zysku produktu.", "Market price from Pricing data. If unavailable, the mod estimates it from cost and the product's optimum profit rate."));
                    CreateMetricLineZone(root, tileRT, "Suggestion", 2, 4, 0.00f, 0.38f,
                        Plugin.T("Sugestia ceny", "Price suggestion"),
                        Plugin.T("Sugerowana cena bazuje na cenie rynkowej i może zostać lekko podniesiona przy rosnącym popycie lub obniżona przy spadku popytu i dużym zapasie. Wynik jest ograniczany bezpiecznym minimum i maksimum.", "Suggested price starts from market price and may be raised slightly with rising demand or lowered with falling demand and excess stock. The result is clamped to safe minimum and maximum bounds."));
                    CreateMetricLineZone(root, tileRT, "Advice", 3, 4, 0.00f, 0.55f,
                        Plugin.T("Rekomendacja cenowa", "Pricing advice"),
                        Plugin.T("Najpierw uzupełnij zapas przy wysokim poziomie braków lub pokryciu poniżej 1 dnia; podwyżka przy silnym wzroście popytu i dobrym zapasie; obniżka przy silnym spadku i nadmiarze zapasu; inaczej pozostaw cenę.", "Restock first when misses are high or cover is below 1 day; raise with strong demand growth and healthy stock; lower with strong decline and excess stock; otherwise keep the price."));
                    CreateMetricLineZone(root, tileRT, "Confidence", 3, 4, 0.70f, 1.00f,
                        Plugin.T("Pewn. = Pewność", "Conf. = Confidence"),
                        Plugin.T("Pewność rekomendacji rośnie wraz z liczbą dni danych i wielkością obserwowanego popytu/sprzedaży. Model waży około 40% długości historii i 60% liczby obserwacji.", "Recommendation confidence increases with the number of days of data and observed demand/sales volume. The model weights roughly 40% history length and 60% evidence volume."));
                    break;

                case AnalysisViewMode.ExpiryRisk:
                    CreateMetricLineZone(root, tileRT, "ExpiryTrackedStock", 0, 5, 0.00f, 0.34f,
                        Plugin.T("Stan", "Stock"),
                        Plugin.T("Łączna ilość produktu objęta aktywnym śledzeniem dat ważności. Dla produktów ważonych wartość jest pokazywana w kilogramach.", "Total quantity of the product covered by active expiry-date tracking. Weighted products are shown in kilograms."));
                    CreateMetricLineZone(root, tileRT, "ExpiryNearest", 0, 5, 0.48f, 0.95f,
                        Plugin.T("Najbliższy termin", "Nearest expiry"),
                        Plugin.T("Najkrótszy pozostały czas do terminu spośród wszystkich śledzonych partii tego produktu.", "Shortest remaining time to expiry among all tracked batches of this product."));
                    CreateMetricLineZone(root, tileRT, "ExpiryExpired", 1, 5, 0.00f, 0.40f,
                        Plugin.T("Po terminie", "Expired"),
                        Plugin.T("Ilość produktu, którego data ważności już minęła.", "Quantity whose expiry date has already passed."));
                    CreateMetricLineZone(root, tileRT, "Expiry1Day", 1, 5, 0.55f, 0.95f,
                        Plugin.T("≤1 dzień", "≤1 day"),
                        Plugin.T("Ilość produktu, która jest już po terminie lub wygaśnie dziś/jutro w zależności od partii. Wskaźnik służy do wykrywania najbardziej pilnego ryzyka.", "Quantity at the most urgent expiry horizon, used to identify stock that requires immediate attention."));
                    CreateMetricLineZone(root, tileRT, "Expiry3Days", 2, 5, 0.00f, 0.40f,
                        Plugin.T("≤3 dni", "≤3 days"),
                        Plugin.T("Ilość produktu, która wygaśnie w ciągu maksymalnie 3 dni gry. Nie obejmuje sztuk już przeterminowanych; te są pokazane osobno.", "Quantity that will expire within at most 3 in-game days. Already expired units are shown separately."));
                    CreateMetricLineZone(root, tileRT, "Expiry7Days", 2, 5, 0.55f, 0.95f,
                        Plugin.T("≤7 dni", "≤7 days"),
                        Plugin.T("Ilość produktu, która wygaśnie w ciągu maksymalnie 7 dni gry. Pomaga wcześniej wychwycić nadmiar zapasu.", "Quantity that will expire within at most 7 in-game days. Helps identify excess stock earlier."));
                    CreateMetricLineZone(root, tileRT, "ExpiryValueRisk", 3, 5, 0.00f, 0.74f,
                        Plugin.T("Ryzyko wartości ≤3 dni", "Value risk ≤3 days"),
                        Plugin.T("Szacowana wartość kosztowa zapasu zagrożonego w horyzoncie 3 dni: (po terminie + ≤3 dni) × bieżący koszt produktu.", "Estimated cost value of stock at risk within the 3-day horizon: (expired + ≤3 days) × current product cost."));
                    CreateMetricLineZone(root, tileRT, "ExpiryRiskLevel", 4, 5, 0.00f, 0.48f,
                        Plugin.T("Ocena ryzyka", "Risk level"),
                        Plugin.T("Syntetyczna ocena pilności oparta na liczbie sztuk po terminie oraz zapasie wygasającym w 1, 3 i 7 dni. Służy głównie do sortowania i szybkiego wskazania produktów wymagających uwagi.", "Priority rating based on expired stock and quantities expiring within 1, 3, and 7 days. It is mainly used for sorting and quickly highlighting products needing attention."));
                    break;
            }
        }

        private void AttachExpirationInfoTooltipZones(
            Transform tile,
            TextMeshProUGUI infoTmp,
            SortedDictionary<int, int> shelfBatches,
            SortedDictionary<int, int> boxBatches)
        {
            if (tile == null || infoTmp == null) return;

            Transform root = BeginMetricTooltipRoot(infoTmp, "ExpirationMetricTooltipZones");
            if (root == null) return;

            RectTransform tileRT = tile.GetComponent<RectTransform>();

            int shelfLines = CountExpirationSectionLines(shelfBatches);
            int boxLines = CountExpirationSectionLines(boxBatches);
            int totalLines = Mathf.Max(1, shelfLines + boxLines);

            float shelfBottom = 1f - shelfLines / (float)totalLines;

            CreateProductInfoTooltipZone(
                root,
                tileRT,
                "ExpiryShelfSection",
                new Vector2(0f, shelfBottom),
                new Vector2(1f, 1f),
                Plugin.T("Terminy na półce", "Shelf expiry dates"),
                Plugin.T(
                    "Pokazuje terminy produktów, które fizycznie znajdują się na półkach lub ekspozycjach sklepu. Daty są posortowane od najpilniejszej. Jeżeli widzisz „+N termin.”, produkt ma jeszcze dodatkowe grupy terminów, których nie pokazujemy na karcie, aby zachować czytelność.",
                    "Shows expiry dates for products physically placed on store shelves or displays. Dates are sorted from the most urgent. “+N more” means there are additional expiry groups hidden to keep the card readable."));

            CreateProductInfoTooltipZone(
                root,
                tileRT,
                "ExpiryBoxesSection",
                new Vector2(0f, 0f),
                new Vector2(1f, shelfBottom),
                Plugin.T("Terminy w kartonach", "Box expiry dates"),
                Plugin.T(
                    "Pokazuje terminy produktów, które nadal znajdują się w kartonach. Obejmuje fizyczne kartony obecne w scenie, dla których mod ma zapisane daty ważności. Daty są posortowane od najpilniejszej.",
                    "Shows expiry dates for products still stored in boxes. It includes physical boxes present in the scene for which the mod has saved expiry dates. Dates are sorted from the most urgent."));
        }

        private void AttachIceCreamInfoTooltipZones(Transform tile, TextMeshProUGUI infoTmp, string body)
        {
            if (tile == null || infoTmp == null || string.IsNullOrEmpty(body)) return;
            Transform root = BeginMetricTooltipRoot(infoTmp, "IceCreamMetricTooltipZones");
            if (root == null) return;
            RectTransform tileRT = tile.GetComponent<RectTransform>();

            string[] lines = body.Split('\n');
            int lineCount = Mathf.Max(1, lines.Length);

            for (int i = 0; i < lines.Length; i++)
            {
                string line = lines[i] ?? string.Empty;

                if (line.Contains(Plugin.T("Sprzedane", "Sold")))
                    CreateMetricLineZone(root, tileRT, "IceSold_" + i, i, lineCount, 0.00f, 0.30f,
                        Plugin.T("Sprzedane lody", "Ice creams sold"),
                        Plugin.T("Liczba gotowych lodów sprzedanych dla tego podsumowania, rożka lub kombinacji.", "Number of finished ice creams sold for this summary, cone, or combination."));

                if (line.Contains(Plugin.T("Lody", "Ice creams")) && !line.Contains(Plugin.T("Lody z tym smakiem", "Ice creams with flavour")))
                    CreateMetricLineZone(root, tileRT, "IceCount_" + i, i, lineCount, 0.00f, 0.30f,
                        Plugin.T("Lody", "Ice creams"),
                        Plugin.T("Liczba gotowych lodów wykorzystujących wskazany rożek.", "Number of finished ice creams using the selected cone."));

                if (line.Contains(Plugin.T("Przychód", "Revenue")) && !line.Contains(Plugin.T("Przychód / Koszt", "Revenue / Cost")))
                    CreateMetricLineZone(root, tileRT, "IceRevenue_" + i, i, lineCount, 0.00f, 0.38f,
                        Plugin.T("Przychód", "Revenue"),
                        Plugin.T("Łączna kwota zapłacona przez klientów za te gotowe lody.", "Total amount paid by customers for these finished ice creams."));

                if (line.Contains(Plugin.T("Koszt", "Cost")) && !line.Contains(Plugin.T("Przychód / Koszt", "Revenue / Cost")))
                    CreateMetricLineZone(root, tileRT, "IceCost_" + i, i, lineCount, 0.00f, 0.34f,
                        Plugin.T("Koszt", "Cost"),
                        Plugin.T("Łączny koszt zużytych składników: koszt rożka plus koszt wszystkich użytych gałek smaków, zapisany przy sprzedaży.", "Total cost of used ingredients: cone cost plus the cost of all flavour scoops, captured at sale time."));

                if (line.Contains(Plugin.T("Zysk / Marża", "Profit / Margin")))
                    CreateMetricLineZone(root, tileRT, "IceProfitMargin_" + i, i, lineCount, 0.00f, 0.48f,
                        Plugin.T("Zysk / Marża", "Profit / Margin"),
                        Plugin.T("Zysk = przychód - koszt składników. Marża = zysk / przychód × 100%.", "Profit = revenue - ingredient cost. Margin = profit / revenue × 100%."));

                if (line.Contains(Plugin.T("Łącznie gałek", "Total scoops")))
                    CreateMetricLineZone(root, tileRT, "TotalScoops_" + i, i, lineCount, 0.00f, 0.46f,
                        Plugin.T("Łącznie gałek", "Total scoops"),
                        Plugin.T("Łączna liczba wszystkich gałek smaków zużytych w sprzedanych lodach.", "Total number of all flavour scoops used in sold ice creams."));

                if (line.Contains(Plugin.T("Śr. gałek / lód", "Avg scoops / ice cream")))
                    CreateMetricLineZone(root, tileRT, "AvgScoops_" + i, i, lineCount, 0.00f, 0.58f,
                        Plugin.T("Średnia liczba gałek", "Average scoops"),
                        Plugin.T("Łączna liczba gałek podzielona przez liczbę sprzedanych lodów.", "Total scoops divided by the number of sold ice creams."));

                if (line.Contains(Plugin.T("Najpopularniejszy rożek", "Top cone")))
                    CreateMetricLineZone(root, tileRT, "TopCone_" + i, i, lineCount, 0.00f, 0.62f,
                        Plugin.T("Najpopularniejszy rożek", "Top cone"),
                        Plugin.T("Rodzaj rożka użyty w największej liczbie sprzedanych lodów.", "Cone type used in the highest number of sold ice creams."));

                if (line.Contains(Plugin.T("Najpopularniejszy smak", "Top flavour")))
                    CreateMetricLineZone(root, tileRT, "TopFlavour_" + i, i, lineCount, 0.00f, 0.62f,
                        Plugin.T("Najpopularniejszy smak", "Top flavour"),
                        Plugin.T("Smak, z którego zużyto najwięcej gałek w sprzedanych lodach.", "Flavour with the highest number of scoops used in sold ice creams."));

                if (line.Contains(Plugin.T("Gałki", "Scoops")))
                    CreateMetricLineZone(root, tileRT, "Scoops_" + i, i, lineCount, 0.34f, 0.58f,
                        Plugin.T("Gałki", "Scoops"),
                        Plugin.T("Liczba gałek smaków w jednym lodzie tej kombinacji.", "Number of flavour scoops in one ice cream of this combination."));

                if (line.Contains(Plugin.T("Topping", "Topping")))
                    CreateMetricLineZone(root, tileRT, "Topping_" + i, i, lineCount, 0.66f, 1.00f,
                        Plugin.T("Topping", "Topping"),
                        Plugin.T("Identyfikator dodatku/toppingu zapisany przez grę dla tej kombinacji. Topping nie ma osobnego ProductSO, więc nie jest doliczany jako magazynowy koszt składnika.", "Topping identifier recorded by the game for this combination. Toppings do not have a separate ProductSO, so they are not added as inventory ingredient cost."));

                if (line.Contains(Plugin.T("Przychód / Koszt", "Revenue / Cost")))
                    CreateMetricLineZone(root, tileRT, "RevenueCost_" + i, i, lineCount, 0.00f, 0.52f,
                        Plugin.T("Przychód / Koszt", "Revenue / Cost"),
                        Plugin.T("Pierwsza wartość to łączny przychód z kombinacji, druga to łączny koszt zużytych rożków i gałek.", "First value is total revenue for the combination; second is the total cost of used cones and scoops."));

                if (line.Contains(Plugin.T("Zużyte gałki", "Scoops used")))
                    CreateMetricLineZone(root, tileRT, "ScoopsUsed_" + i, i, lineCount, 0.00f, 0.50f,
                        Plugin.T("Zużyte gałki", "Scoops used"),
                        Plugin.T("Łączna liczba gałek danego smaku zużytych we wszystkich sprzedanych lodach.", "Total number of scoops of this flavour used across all sold ice creams."));

                if (line.Contains(Plugin.T("Lody z tym smakiem", "Ice creams with flavour")))
                    CreateMetricLineZone(root, tileRT, "IceWithFlavour_" + i, i, lineCount, 0.00f, 0.64f,
                        Plugin.T("Lody z tym smakiem", "Ice creams with flavour"),
                        Plugin.T("Liczba sprzedanych lodów, w których wystąpił ten smak co najmniej raz.", "Number of sold ice creams in which this flavour appeared at least once."));

                if (line.Contains(Plugin.T("Udział w gałkach", "Share of scoops")))
                    CreateMetricLineZone(root, tileRT, "ScoopShare_" + i, i, lineCount, 0.00f, 0.58f,
                        Plugin.T("Udział w gałkach", "Share of scoops"),
                        Plugin.T("Procent wszystkich zużytych gałek, który przypada na ten smak.", "Percentage of all used scoops represented by this flavour."));

                if (line.Contains(Plugin.T("Śr. gałek w takim lodzie", "Avg scoops when used")))
                    CreateMetricLineZone(root, tileRT, "AvgFlavourScoops_" + i, i, lineCount, 0.00f, 0.72f,
                        Plugin.T("Średnia gałek tego smaku", "Average scoops of this flavour"),
                        Plugin.T("Średnia liczba gałek tego smaku w lodach, które zawierały ten smak.", "Average number of scoops of this flavour in ice creams that contained the flavour."));
            }
        }

        private void AttachDailySummaryCardTooltips(GameObject card, TextMeshProUGUI titleTmp, TextMeshProUGUI detailsTmp, string cardTitle)
        {
            if (card == null || titleTmp == null) return;
            RectTransform cardRT = card.GetComponent<RectTransform>();

            if (TryGetSummaryCardTooltip(cardTitle, out string title, out string body))
            {
                Transform root = BeginMetricTooltipRoot(titleTmp, "CardTitleTooltipZone");
                if (root != null)
                {
                    CreateProductInfoTooltipZone(root, cardRT, "Title", Vector2.zero, Vector2.one, title, body);
                }
            }

            AttachSummaryCardDetailTooltips(cardRT, detailsTmp, cardTitle);
        }

        private void AttachSummaryCardDetailTooltips(RectTransform cardRT, TextMeshProUGUI detailsTmp, string cardTitle)
        {
            if (cardRT == null || detailsTmp == null || string.IsNullOrEmpty(detailsTmp.text)) return;
            Transform root = BeginMetricTooltipRoot(detailsTmp, "CardDetailTooltipZones");
            if (root == null) return;
            string text = detailsTmp.text;

            bool IsCard(string pl, string en) => cardTitle == Plugin.T(pl, en);

            void AddIf(string labelPl, string labelEn, float xMin, float xMax, string tipPl, string tipEn)
            {
                string label = Plugin.T(labelPl, labelEn);
                if (text.IndexOf(label, StringComparison.OrdinalIgnoreCase) < 0) return;
                CreateProductInfoTooltipZone(root, cardRT, "Detail_" + labelEn.Replace(" ", "_"), new Vector2(xMin, 0f), new Vector2(xMax, 1f), label, Plugin.T(tipPl, tipEn));
            }

            if (IsCard("KLIENCI", "CUSTOMERS"))
            {
                AddIf("Zadowoleni", "Satisfied", 0.00f, 0.48f,
                    "Liczba klientów oznaczonych przez grę jako zadowoleni w tym dniu.",
                    "Number of customers marked by the game as satisfied on this day.");
            }
            else if (IsCard("PROBLEMY Z PRODUKTAMI", "PRODUCT ISSUES"))
            {
                AddIf("Brak", "Not found", 0.00f, 0.45f,
                    "Liczba przypadków, w których klient nie znalazł produktu.",
                    "Number of cases where a customer could not find a product.");
                AddIf("Za drogo", "Too expensive", 0.52f, 1.00f,
                    "Liczba przypadków, w których klient uznał produkt za zbyt drogi.",
                    "Number of cases where a customer considered a product too expensive.");
            }
            else if (IsCard("BŁĘDY OBSŁUGI", "SERVICE ISSUES"))
            {
                AddIf("Reszta", "Short change", 0.00f, 0.45f,
                    "Liczba przypadków niepoprawnie wydanej reszty zapisana przez grę.",
                    "Number of incorrect-change cases recorded by the game.");
                AddIf("Poszkodowani", "Harmed", 0.52f, 1.00f,
                    "Liczba klientów oznaczonych przez grę jako poszkodowani przez obsługę.",
                    "Number of customers marked by the game as harmed by service.");
            }
            else if (IsCard("POZOSTAŁE WPŁYWY", "OTHER INCOME"))
            {
                AddIf("Automaty", "Vending", 0.00f, 0.45f,
                    "Wpływy ze sprzedaży w automatach vendingowych zapisane w podsumowaniu dnia.",
                    "Income from vending-machine sales recorded in the daily summary.");
                AddIf("Pożyczki", "Loans", 0.52f, 1.00f,
                    "Wpływy z zaciągniętych pożyczek. To finansowanie, a nie przychód ze sprzedaży.",
                    "Inflows from loans. This is financing, not sales revenue.");
            }
            else if (IsCard("CZYNSZ I RACHUNKI", "RENT AND BILLS"))
            {
                AddIf("Czynsz", "Rent", 0.00f, 0.45f,
                    "Koszt czynszu za sklep zapisany przez grę dla tego dnia.",
                    "Store rent cost recorded by the game for this day.");
                AddIf("Rachunki", "Bills", 0.52f, 1.00f,
                    "Koszt rachunków zapisany przez grę dla tego dnia.",
                    "Bills cost recorded by the game for this day.");
            }
            else if (IsCard("INWESTYCJE", "INVESTMENTS"))
            {
                AddIf("Ulepszenia", "Upgrades", 0.00f, 0.45f,
                    "Wydatki na ulepszenia sklepu w tym dniu.",
                    "Spending on store upgrades on this day.");
                AddIf("Wystrój", "Customization", 0.52f, 1.00f,
                    "Wydatki na personalizację/wystrój sklepu w tym dniu.",
                    "Spending on store customization on this day.");
            }
            else if (IsCard("ZYSK DNIA", "DAILY PROFIT"))
            {
                AddIf("Wyliczenie moda", "Mod calculation", 0.00f, 0.62f,
                    "Kontrolne wyliczenie: łączne wpływy minus wszystkie zapisane wydatki. Służy do porównania z natywnym Zyskiem dnia gry.",
                    "Control calculation: total income minus all recorded expenses. Used to compare with the game's native Daily profit.");
            }
            else if (IsCard("TRANSAKCJE KASOWE", "CHECKOUT TRANSACTIONS"))
            {
                AddIf("PRZYCHÓD KAS", "CHECKOUT REVENUE", 0.00f, 0.50f,
                    "Przychód z transakcji przy kasach, bez zamówień online i automatów.",
                    "Revenue from checkout transactions, excluding online orders and vending machines.");
                AddIf("ŚREDNI KOSZYK", "AVERAGE BASKET", 0.52f, 1.00f,
                    "Przychód kas podzielony przez liczbę transakcji kasowych.",
                    "Checkout revenue divided by the number of checkout transactions.");
            }
            else if (IsCard("KARTA", "CARD") || IsCard("GOTÓWKA", "CASH") ||
                     IsCard("SELF-CHECKOUT", "SELF CHECKOUT") || IsCard("KASJER", "CASHIER") ||
                     IsCard("GRACZ", "PLAYER") || IsCard("KASA TRADYCYJNA", "REGULAR CHECKOUT"))
            {
                AddIf("PRZYCHÓD", "REVENUE", 0.00f, 0.38f,
                    "Przychód przypisany do wskazanego kanału lub typu transakcji.",
                    "Revenue attributed to the selected channel or transaction type.");
                AddIf("ŚREDNI KOSZYK", "AVERAGE BASKET", 0.48f, 1.00f,
                    "Przychód kanału podzielony przez liczbę jego transakcji.",
                    "Channel revenue divided by its number of transactions.");
            }
            else if (IsCard("ZAMÓWIENIA ONLINE", "ONLINE ORDERS") || IsCard("AUTOMATY VENDINGOWE", "VENDING MACHINES"))
            {
                AddIf("PRZYCHÓD", "REVENUE", 0.00f, 0.38f,
                    "Przychód przypisany do wskazanego kanału sprzedaży.",
                    "Revenue attributed to the selected sales channel.");
                AddIf("ŚREDNIA TRANSAKCJA", "AVERAGE TRANSACTION", 0.48f, 1.00f,
                    "Przychód kanału podzielony przez liczbę transakcji w tym kanale.",
                    "Channel revenue divided by the number of transactions in that channel.");
            }
        }

        private bool TryGetSummaryCardTooltip(string cardTitle, out string title, out string body)
        {
            title = cardTitle ?? string.Empty;
            body = string.Empty;
            if (string.IsNullOrEmpty(cardTitle)) return false;

            bool Is(string pl, string en) => cardTitle == Plugin.T(pl, en);

            if (Is("TRANSAKCJE", "TRANSACTIONS"))
                body = Plugin.T("Liczba zakończonych transakcji przy kasach zarejestrowanych przez tracker koszyków.", "Number of completed checkout transactions recorded by the basket tracker.");
            else if (Is("ŚREDNI KOSZYK", "AVERAGE BASKET"))
                body = Plugin.T("Łączny przychód z koszyków podzielony przez liczbę zakończonych transakcji.", "Total basket revenue divided by the number of completed transactions.");
            else if (Is("SZTUK NA KOSZYK", "ITEMS PER BASKET"))
                body = Plugin.T("Łączna liczba kupionych sztuk podzielona przez liczbę zakończonych transakcji.", "Total purchased items divided by the number of completed transactions.");
            else if (Is("PRZYCHÓD / KLIENT", "REVENUE PER CUSTOMER"))
                body = Plugin.T("Dochód z kas podzielony przez liczbę klientów zarejestrowanych przez grę.", "Checkout income divided by the number of customers recorded by the game.");
            else if (Is("KLIENCI", "CUSTOMERS"))
                body = Plugin.T("Łączna liczba klientów zarejestrowanych przez grę dla wybranego dnia.", "Total number of customers recorded by the game for the selected day.");
            else if (Is("SATYSFAKCJA", "SATISFACTION"))
                body = Plugin.T("Zadowoleni klienci / wszyscy klienci × 100%.", "Satisfied customers / all customers × 100%.");
            else if (Is("BRAK PRODUKTU", "NOT FOUND RATE"))
                body = Plugin.T("Klienci, którzy nie znaleźli produktu / wszyscy klienci × 100%.", "Customers who could not find a product / all customers × 100%.");
            else if (Is("ZA DROGO", "TOO EXPENSIVE RATE"))
                body = Plugin.T("Klienci z reakcją 'za drogo' / wszyscy klienci × 100%.", "Customers with a 'too expensive' reaction / all customers × 100%.");
            else if (Is("WSZYSTKIE TRANSAKCJE", "ALL TRANSACTIONS"))
                body = Plugin.T("Suma śledzonych transakcji ze wszystkich kanałów sprzedaży: kasy, zamówienia online oraz automaty vendingowe, jeśli są dostępne.", "Sum of tracked transactions across all sales channels: checkouts, online orders, and vending machines when available.");
            else if (Is("ŁĄCZNY PRZYCHÓD", "TOTAL REVENUE"))
                body = Plugin.T("Łączny przychód ze wszystkich śledzonych kanałów sprzedaży. Pożyczki nie są tu traktowane jako sprzedaż.", "Total revenue from all tracked sales channels. Loans are not treated as sales here.");
            else if (Is("TRANSAKCJE KASOWE", "CHECKOUT TRANSACTIONS"))
                body = Plugin.T("Liczba zakończonych transakcji przy kasach. Karta pokazuje także przychód kas i średni koszyk.", "Number of completed checkout transactions. The card also shows checkout revenue and average basket.");
            else if (Is("KARTA", "CARD"))
                body = Plugin.T("Liczba i udział transakcji opłaconych kartą wśród transakcji, dla których metoda płatności została poprawnie zarejestrowana.", "Count and share of card-paid transactions among transactions whose payment method was reliably recorded.");
            else if (Is("GOTÓWKA", "CASH"))
                body = Plugin.T("Liczba i udział transakcji opłaconych gotówką wśród transakcji, dla których metoda płatności została poprawnie zarejestrowana.", "Count and share of cash-paid transactions among transactions whose payment method was reliably recorded.");
            else if (Is("SELF-CHECKOUT", "SELF CHECKOUT"))
                body = Plugin.T("Liczba i udział transakcji obsłużonych przez kasy samoobsługowe.", "Count and share of transactions handled by self-checkouts.");
            else if (Is("KASJER", "CASHIER"))
                body = Plugin.T("Liczba i udział transakcji obsłużonych przez zatrudnionego kasjera.", "Count and share of transactions handled by an employed cashier.");
            else if (Is("GRACZ", "PLAYER"))
                body = Plugin.T("Liczba i udział transakcji obsłużonych bezpośrednio przez gracza.", "Count and share of transactions handled directly by the player.");
            else if (Is("KASA TRADYCYJNA", "REGULAR CHECKOUT"))
                body = Plugin.T("Łącznie transakcje na tradycyjnych kasach: kasjer + gracz.", "Combined regular-checkout transactions: cashier + player.");
            else if (Is("ZAMÓWIENIA ONLINE", "ONLINE ORDERS"))
                body = Plugin.T("Liczba, udział i przychód z zakończonych zamówień online śledzonych przez mod.", "Count, share, and revenue from completed online orders tracked by the mod.");
            else if (Is("AUTOMATY VENDINGOWE", "VENDING MACHINES"))
                body = Plugin.T("Liczba, udział i przychód ze sprzedaży w automatach vendingowych. Karta jest ukrywana, jeśli DLC/funkcja automatów nie jest dostępna.", "Count, share, and revenue from vending-machine sales. The card is hidden if vending content is not available.");
            else if (Is("PROBLEMY Z PRODUKTAMI", "PRODUCT ISSUES"))
                body = Plugin.T("Suma problemów produktowych z podsumowania dnia: nie znaleziono produktu + produkt za drogi.", "Sum of product issues from the daily summary: product not found + product too expensive.");
            else if (Is("BŁĘDY OBSŁUGI", "SERVICE ISSUES"))
                body = Plugin.T("Suma błędów obsługi z podsumowania dnia: niepoprawna reszta + poszkodowani klienci.", "Sum of service issues from the daily summary: incorrect change + harmed customers.");
            else if (Is("PUNKTY SKLEPU", "STORE POINTS"))
                body = Plugin.T("Punkty sklepu przyznane przez grę w zakończonym dniu.", "Store points awarded by the game on the completed day.");
            else if (Is("DOCHÓD Z KAS", "CHECKOUT INCOME"))
                body = Plugin.T("Natywny dochód ze sprzedaży przy kasach przekazany przez grę do ekranu podsumowania dnia.", "Native checkout sales income passed by the game to the daily summary screen.");
            else if (Is("POZOSTAŁE WPŁYWY", "OTHER INCOME"))
                body = Plugin.T("Suma wpływów z automatów vendingowych i pożyczek. Pożyczki są finansowaniem, nie sprzedażą.", "Sum of vending income and loan inflows. Loans are financing, not sales.");
            else if (Is("ŁĄCZNE WPŁYWY", "TOTAL INCOME"))
                body = Plugin.T("Dochód z kas + automaty vendingowe + wpływy z pożyczek.", "Checkout income + vending income + loan inflows.");
            else if (Is("ZAOPATRZENIE", "SUPPLIES"))
                body = Plugin.T("Koszt zamówionego towaru zapisany przez grę w podsumowaniu dnia.", "Cost of ordered stock recorded by the game in the daily summary.");
            else if (Is("PERSONEL", "STAFF"))
                body = Plugin.T("Łączne wynagrodzenia pracowników naliczone w tym dniu.", "Total employee wages charged on this day.");
            else if (Is("CZYNSZ I RACHUNKI", "RENT AND BILLS"))
                body = Plugin.T("Łączny koszt czynszu i rachunków w wybranym dniu.", "Combined rent and bills cost on the selected day.");
            else if (Is("INWESTYCJE", "INVESTMENTS"))
                body = Plugin.T("Łączne wydatki inwestycyjne/personalizacyjne zapisane tego dnia, w tym ulepszenia i wystrój oraz powiązane koszty.", "Combined investment/customization spending recorded that day, including upgrades and customization-related costs.");
            else if (Is("SPŁATA POŻYCZKI", "LOAN PAYMENT"))
                body = Plugin.T("Kwota raty pożyczki zapłacona w tym dniu.", "Loan repayment amount paid on this day.");
            else if (Is("ŁĄCZNE WYDATKI", "TOTAL EXPENSES"))
                body = Plugin.T("Suma bezwzględnych wartości wszystkich zapisanych kosztów dnia: zaopatrzenie, personel, czynsz, rachunki, inwestycje, spłata pożyczki i inne zapisane kategorie.", "Sum of absolute values of all recorded daily expenses: supplies, staff, rent, bills, investments, loan repayment, and other recorded categories.");
            else if (Is("ZYSK DNIA", "DAILY PROFIT"))
                body = Plugin.T("Zysk dnia przekazany przez grę do podsumowania. Niżej mod pokazuje własne kontrolne wyliczenie: łączne wpływy minus zapisane wydatki.", "Daily profit passed by the game to the summary. The mod also shows a control calculation: total income minus recorded expenses.");
            else if (Is("SALDO", "BALANCE"))
                body = Plugin.T("Stan konta zapisany przez grę po zakończeniu wybranego dnia.", "Account balance recorded by the game after the selected day ended.");
            else
                return false;

            return true;
        }

        private void AttachChartMetricTooltip(TextMeshProUGUI label)
        {
            if (label == null || _categoryCycleBtn == null) return;
            string metric = GetActiveChartMetricLabel();
            if (!TryGetChartMetricTooltip(metric, out string title, out string body)) return;

            // IMPORTANT: nie tworzymy tutaj przezroczystej strefy EventTrigger jako
            // dziecka przycisku. EventTrigger implementuje IPointerClickHandler i wtedy
            // przechwytuje kliknięcie zanim trafi ono do Buttona „Kategoria”.
            // Tooltip podpinamy bezpośrednio do tego samego GameObject co Button.
            label.raycastTarget = false;

            RectTransform buttonRT = _categoryCycleBtn.GetComponent<RectTransform>();
            if (buttonRT == null) return;

            var trigger = _categoryCycleBtn.GetComponent<EventTrigger>();
            if (trigger == null)
                trigger = _categoryCycleBtn.gameObject.AddComponent<EventTrigger>();

            // Ten EventTrigger należy tylko do naszego przycisku kategorii.
            // Czyścimy poprzednie wpisy, bo etykieta/metryka jest aktualizowana po kliknięciu.
            trigger.triggers.Clear();

            AddTooltipEvent(trigger, EventTriggerType.PointerEnter,
                (UnityAction<BaseEventData>)((_) => ShowProductInfoTooltip(buttonRT, buttonRT, title, body)));
            AddTooltipEvent(trigger, EventTriggerType.PointerExit,
                (UnityAction<BaseEventData>)((_) => HideProductInfoTooltip()));
        }

        private bool TryGetChartMetricTooltip(string metric, out string title, out string body)
        {
            title = metric ?? string.Empty;
            body = string.Empty;
            if (string.IsNullOrEmpty(metric)) return false;

            bool Is(string pl, string en) => metric == Plugin.T(pl, en);

            if (Is("Sprzedane", "Sold"))
                body = Plugin.T("Wykres pokazuje ilość sprzedaną w kolejnych dniach. Dla produktów ważonych wartości są w kg.", "Chart shows sold quantity across days. Weighted products are shown in kg.");
            else if (Is("Wartość sprzedaży", "Sales Revenue"))
                body = Plugin.T("Wykres pokazuje dzienny przychód ze sprzedaży wybranego produktu.", "Chart shows daily sales revenue for the selected product.");
            else if (Is("Wyrzucone", "Wasted"))
                body = Plugin.T("Wykres pokazuje ilość produktu wyrzuconą/utraconą w kolejnych dniach.", "Chart shows quantity discarded/lost across days.");
            else if (Is("Wartość strat", "Wastage Loss"))
                body = Plugin.T("Wykres pokazuje wartość strat wynikających z wyrzuconego towaru w kolejnych dniach.", "Chart shows the value of wastage losses across days.");
            else if (Is("Łączna liczba klientów", "Total customers"))
                body = Plugin.T("Liczba wszystkich klientów zarejestrowanych przez grę dla każdego dnia.", "Number of all customers recorded by the game for each day.");
            else if (Is("Zadowoleni klienci", "Satisfied customers"))
                body = Plugin.T("Liczba klientów oznaczonych przez grę jako zadowoleni w każdym dniu.", "Number of customers marked by the game as satisfied each day.");
            else if (Is("Poziom zadowolenia", "Satisfaction rate"))
                body = Plugin.T("Zadowoleni klienci / wszyscy klienci × 100% dla każdego dnia.", "Satisfied customers / all customers × 100% for each day.");
            else if (Is("Nie znaleziono produktów", "Products not found"))
                body = Plugin.T("Liczba problemów, w których klienci nie znaleźli produktów w danym dniu.", "Number of product-not-found issues on each day.");
            else if (Is("Produkty za drogie", "Products too expensive"))
                body = Plugin.T("Liczba przypadków reakcji klientów na zbyt wysoką cenę w danym dniu.", "Number of customer too-expensive reactions on each day.");
            else if (Is("Niepoprawna reszta", "Incorrect change"))
                body = Plugin.T("Liczba przypadków niepoprawnie wydanej reszty w danym dniu.", "Number of incorrect-change cases on each day.");
            else if (Is("Poszkodowani klienci", "Harmed customers"))
                body = Plugin.T("Liczba klientów oznaczonych przez grę jako poszkodowani w danym dniu.", "Number of customers marked by the game as harmed on each day.");
            else if (Is("Punkty sklepu", "Store points"))
                body = Plugin.T("Punkty sklepu uzyskane w każdym zakończonym dniu.", "Store points earned on each completed day.");
            else if (Is("Dochód z kas", "Checkout income"))
                body = Plugin.T("Natywny dzienny dochód ze sprzedaży przy kasach.", "Native daily income from checkout sales.");
            else if (Is("Dochód z automatów", "Vending income"))
                body = Plugin.T("Dzienny przychód z automatów vendingowych.", "Daily vending-machine income.");
            else if (Is("Wpływy z pożyczki", "Loan income"))
                body = Plugin.T("Kwota wpływów z pożyczek w danym dniu. To finansowanie, nie sprzedaż.", "Loan inflows on each day. This is financing, not sales.");
            else if (Is("Łączne wpływy", "Total income"))
                body = Plugin.T("Dochód z kas + automaty + pożyczki dla każdego dnia.", "Checkout income + vending + loans for each day.");
            else if (Is("Zaopatrzenie", "Supply costs"))
                body = Plugin.T("Dzienny koszt zamówionego towaru.", "Daily cost of ordered stock.");
            else if (Is("Personel", "Staff payment"))
                body = Plugin.T("Dzienny koszt wynagrodzeń pracowników.", "Daily employee wage cost.");
            else if (Is("Wynajem", "Rent"))
                body = Plugin.T("Dzienny koszt czynszu.", "Daily rent cost.");
            else if (Is("Rachunki", "Bills"))
                body = Plugin.T("Dzienny koszt rachunków.", "Daily bills cost.");
            else if (Is("Ulepszenia", "Upgrades"))
                body = Plugin.T("Dzienny koszt ulepszeń sklepu.", "Daily store-upgrade cost.");
            else if (Is("Modernizacja", "Customization"))
                body = Plugin.T("Dzienny koszt personalizacji/modernizacji sklepu.", "Daily store customization cost.");
            else if (Is("Spłata pożyczki", "Loan payment"))
                body = Plugin.T("Kwota spłaty pożyczki w każdym dniu.", "Loan repayment amount on each day.");
            else if (Is("Malowanie", "Paint costs"))
                body = Plugin.T("Koszty malowania zapisane w danym dniu.", "Paint costs recorded on each day.");
            else if (Is("Podłogi", "Floor costs"))
                body = Plugin.T("Koszty podłóg zapisane w danym dniu.", "Floor costs recorded on each day.");
            else if (Is("Łączne wydatki", "Total expenses"))
                body = Plugin.T("Suma wszystkich zapisanych kosztów dla każdego dnia.", "Sum of all recorded expenses for each day.");
            else if (Is("Zysk dnia", "Daily profit"))
                body = Plugin.T("Natywny zysk dnia przekazany przez grę do podsumowania.", "Native daily profit passed by the game to the summary.");
            else if (Is("Saldo", "Balance"))
                body = Plugin.T("Stan konta po zakończeniu każdego dnia.", "Account balance after each day ended.");
            else
                return false;

            return true;
        }
    }
}
